### ISSUE TITLE
Auto Save on blur

### ISSUE THREAD

**Issue by xbral** [Rocketseat/unform#108]
Auto Save on blur, select or check

An option to set Form with prop autoSave and when this props was seted the form will save automatically when the user blur the input or select an option

**Comment by converge** [comment]
It's a nice approach, but I believe this is a non-trivial case, and it would require a backend implementation to handle with the API call the onBlur would send. Does it make sense?

**Comment by dope** [comment]
I'm not sure its something that would be heavily needed but you could just store this with `localStorage`.

**Comment by diego3g** [comment]
@xbral Please, use the issue templates for the next issues :)

I think the best approach in this case is if you extend unform Input and add some onBlur functionality to it, every unform input is a HTML input and it can receives all HTML properties like onBlur so you can add your own functionality to it.

**Comment by xbral** [comment]
> @xbral Please, use the issue templates for the next issues :)
> 
> I think the best approach in this case is if you extend unform Input and add some onBlur functionality to it, every unform input is a HTML input and it can receives all HTML properties like onBlur so you can add your own functionality to it.

Sorry @diego3g 

Great. I'll try, and the option to use localStorage is cool. I will use these two ideas together.
