### ISSUE TITLE
Loss of properties when using styled-component

### ISSUE THREAD

**Issue by Fagneregomes** [Rocketseat/unform#109]
**Description of bug**
When transforming component into a styled-component it loses properties as the type.

**To Reproduce**

1. Create a styled-component with the input type unform
ex: 
```
import { Form, Input } from "@rocketseat/unform";
const InputText = styled(Input)`
  display: block;
`;
```
2. import or component
3. try changing the type to number

**Expected behavior**

list all properties

**Comment by diego3g** [comment]
Hi @Fagneregomes, can you provide us a code sandbox demonstrating the code?

**Comment by linconkusunoki** [comment]
Hello @diego3g I'm facing the same problem, here is the [codesandbox](https://codesandbox.io/s/empty-sky-pmell)

**Comment by jpdemagalhaes** [comment]
@linconkusunoki I just checked your sandbox, and it is missing a `name` prop so we can register the field, that is why you're running into an error.

I've forked your sandbox, providing the correct fixes:

https://codesandbox.io/s/agitated-water-xd287

**Comment by linconkusunoki** [comment]
@jpdemagalhaes oh... I did not realize this error, yet I think it's a good idea return a better error message in this case. I also have added the type="number" to test the original error and its working properly

**Comment by jpedroschmitz** [comment]
I'll be closing this @Fagneregomes as it seems that @jpdemagalhaes solved the problem.

But feel free to reopen this issue in case you feel like we missed something ❤️
