### ISSUE TITLE
Discord channel

### ISSUE THREAD

**Issue by converge** [Rocketseat/unform#113]
**What would you like to be added**:

Let's create a Discord channel for the project? We could have it on Rocketseat Discord server I believe.

**Why is this needed**:

Questions and Answers community channel.

**Comment by diego3g** [comment]
Hi @converge, good idea! i'll think about creating it inside Rocketseat server or about creating a new server.

**Comment by jpedroschmitz** [comment]
Hey @converge, we have created a #open-source channel in our [Discord community](https://discordapp.com/invite/gCRAFhc). There we can talk about Unform, propose new features and fill some doubts/questions 💜
