### ISSUE TITLE
Select does not change initialState when rendering again. 

### ISSUE THREAD

**Issue by joaogn** [Rocketseat/unform#116]
**Description of bug**

Select does not change initialState when rendering again.

**To Reproduce**

1. I will make the first render, set the initialState.
2. When rendering, input and selects are set to initialState.
3. Changing the first select changes the react states.
4. When changing states react will again render input changes to new states but selects do not change.

**Screenshots**

      telaChange = (selectedOption:any) => {
          const { telas } = this.props;
          const tela = telas[selectedOption.target.value - 1];
          const { nometela, subtelaqtd, turnoqtd } = tela;
          this.setState({
                  telaselect: parseInt(selectedOption.target.value),
                  nometela,
                  subtelaqtd,
                  turnoqtd,
          });
        };
    
    
    render() {
        const {
          telaselect,
          nometela,
          subtelaqtd,
          turnoqtd,
        } = this.state;
    
        const formData = {
          telaselect,
          nometela,
          subtelaqtd,
          turnoqtd,
        };
    
          return (
              {console.log(formData)}
              <Form initialData={formData} schema={schema} onSubmit={this.handleSubmit}>
                  <Select 
    					  className="input",
    					  name="telaselect" ,
    					  options={this.telasOptions()} ,
    					  onChange={this.telaChange} />
                  <Input className="input" name="nometela" type="name" placeholder="Nome" />
                  <Select className="input" name="subtelaqtd" options={subtelasOptions} />
                  <Select className="input" name="turnoqtd" options={turnoOptions} />
                  <button className="form-btn" type="submit">Editar tela</button>
              </Form>
    		)

![bug unform](https://raw.githubusercontent.com/joaogn/my-random-web/master/bug%20Select%20unform.png "bug unform")

**Environment:**

 - OS: Ubuntu
 - Browser Chrome (75.0.3770.142),
 - Node [10.16.0]
 - create-react-app --typescript

**Comment by joaogn** [comment]
I've been thinking, I had a problem updating props, the component didn't reload, so I forced reloading by componentWillReceiveProps (), maybe that wouldn't solve this problem? I just don't know how to approach this using the hooks.

**Comment by meneman** [comment]
Hi, I've been struggling with the same problem. Changing the initialdata property on Form does not rerender the select inputs.
Does anyone have an update on that? 

Shouldnt a change to initialData just rerender the whole form?

**Comment by diego3g** [comment]
Unform released version 2.0 🎉

With that, we do not have a Select component exported inside Unform library, so you'll need to create one using our `useField` API, but i highly recommend you using [React Select](https://unform.dev/third-party/react-select) instead of HTML Select.

Also, `initialData` is used only when the data is synchronously available. If you need to set the data after an API call, use the form `setData` method instead.

Check this: https://unform.dev/guides/initial-data#set-initial-data-asynchronously

**Comment by AdilsonLopesDev** [comment]
Hello Devs, I hope you are all well.
how could i use unForm with the react sematic-ui library?
I would like to be able to use unform with this library.
Someone could help with that.
