### ISSUE TITLE
Infinite render on DatePicker example, when using eslint and prettier.

### ISSUE THREAD

**Issue by emilioheinz** [Rocketseat/unform#117]
**Description of issue**

When I copy and paste the example of the documentation of DatePicker it render infinitely times, this bug do the browser use a lot of memory and after some time crash.

That bug happened because of my eslint + prettier config, both changed my useEffect dependencies to `[fieldName, registerField]` but the right one are `[ref.current, fieldName]`.

I solved the issue adding a `eslint-disable-next-line` on my code.

Like this:
```js
useEffect(() => {
    registerField({
      name: fieldName,
      ref: ref.current,
      path: 'props.selected',
      clearValue: pickerRef => {
        pickerRef.clear()
      },
    })
    // eslint-disable-next-line
  }, [ref.current, fieldName])
```

It would be good add a warning on the documentation to the new users of the lib to take care of that, because it is a little tricky.

I mean something like:
**Observation:** If you are using `eslint + prettier` you need to look for your `useEffect` dependencies, they will change when you format your code and that will cause a bug of infinite render. You can fix it adding a `eslint-disable-next-line` comment on the line above of the `useEffect` dependencies.

OBS: I don't also if the right place to put this is on the documentation, is there a wiki or a common issues page?

**Comment by diego3g** [comment]
Great @emilioheinz, we're investigating problems regarding the hooks rules inside ESLint. I think that for now we should only add one line inside the custom elements documentation here inside Github. Can you open a Pull Request adding the instructions for users to disable ESLint verification in that line?

**Comment by emilioheinz** [comment]
Yess I can, I'll do it and open a pull request.
