### ISSUE TITLE
Mask for Input text

### ISSUE THREAD

**Issue by leoferreiralima** [Rocketseat/unform#122]
**What would you like to be added**:
Mask for Input text

**Why is this needed**:

To make easier and more beautiful for user add phone, email,cpf,cep or any other information that need a mask without need external libs.
The idea is add a new prop for input text name mask,this props will receive a string like "999.999.999-99" so when user add the information will be formatted with the mask.A example below:

```
<Form>
      <Input name="name" />
      <Input name="cep" mask="99.999-999" />
      <Input name="phone" mask="(99) 9 9999-9999" />
      <button type="submit">Send</button>
</Form>
```

**Comment by diego3g** [comment]
I think unform should not implement masks itself but we could have a documentation about how to implement it with some third-party library. Are you using any library for react masks ou recommend one?

**Comment by carvalhoviniciusluiz** [comment]
It would be amazing to be able to format the string if necessary. In parallel to [vue-the-mask](https://vuejs-tips.github.io/vue-the-mask/), unform could support or allow customizing the value with some kind of lib [react-input-mask](https://www.npmjs.com/package/react-input-mask).

I wish I could mask the form inputs, how do you do that?

**Comment by beatriz-evocorp** [comment]
This worked perfectly.

```
<InputMask mask="99/99/9999">
  {() => <Input name="date" required />}
</InputMask>
```

**Comment by beatrizf13** [comment]
This worked perfectly.

```
<InputMask mask="99/99/9999">
  {() => <Input name="date" required />}
</InputMask>
```

**Comment by Natanniel** [comment]
@beatrizf13 Serious O.O ? Let's use

**Comment by carvalhoviniciusluiz** [comment]
For some cases react-input-mask are not applicable, for example using the disabled attribute in the field, this causes an error.

**Comment by santospatrick** [comment]
@beatrizf13 any ideas of an easy way to unmask on `onSubmit`?

**Comment by ggaj** [comment]
Hi Folks,

A problem to use unform(label) + react-input-mask..

```error
Error: react-input-mask: inputComponent doesn't contain input node
```

**Comment by diego3g** [comment]
Unform released version 2.0 🎉

And now, it's easier for you to create your custom inputs, we also have a documentation about creating inputs with masks, check this guide: https://unform.dev/third-party/react-input-mask

**Comment by heniotakatuji** [comment]
https://unform.dev/third-party/react-input-mask

Page not found

**Comment by WellsSA** [comment]
https://unform.dev/examples/react-input-mask

It simply doesn't worked for me.

I got the following error on `<InputMask name="phone" mask="(999) 999-999" />`: 
```ts
useField.ts:24 Uncaught (in promise) TypeError: Cannot read property 'phone' of undefined
    at useField (useField.ts:24)
    at InputMask (index.jsx:8)
    at renderWithHooks (react-dom.development.js:16260)
    at mountIndeterminateComponent (react-dom.development.js:18794)
    at beginWork$1 (react-dom.development.js:20162)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
```

**Comment by eugustavo** [comment]
> }

I tried to use this code and an error was returned.
I removed the function from inside the **InputMask** and left only the **Input** and it worked 😁
`
<InputMask mask="99999-999">
       <Input name="zipcode" placeholder="CEP da sua cidade" />
</InputMask>
`

**Comment by AndresdoSantos** [comment]
Hi guys, any ideas on how to do with React Native? Using TypeScript?
