### ISSUE TITLE
Add new prop 'method' to form

### ISSUE THREAD

**Issue by DanielDavidDev** [Rocketseat/unform#124]
**What would you like to be added**:

Adding a prop to form:

```js
<Form method="post">
...
</Form>
```
And now the prop method, will have api requests directly saying which method will be used.

**Why is this needed**:

Because it's more interesting for the passage of sensitive data.

**Is your enhancement request related to a problem? Please describe.**

No.

**Additional context**

HTML already do this way, so why not :)

**Comment by diego3g** [comment]
@DanielDavidDev As default, our form accepts all of default properties of HTML form.

**Comment by DanielDavidDev** [comment]
Would it be more user friendly to have your sensitive data encrypted? By going through onSubmit because by going through `console.log` you can view the data that is passed to the request.

**Comment by diego3g** [comment]
There is no way to hide all the data as the data is on front-end. And it should not be a problem.

**Comment by DanielDavidDev** [comment]
Got it, so I'll discard this issue, sorry for the inconvenience.
