### ISSUE TITLE
In Choice example, this component not imported in under scope

### ISSUE THREAD

**Issue by murilokaos** [Rocketseat/unform#127]
**In the example for using multiple Choice values, the Choice component is not imported in scope. Apparently, the example was based on the previous example, FileInput, and the import of FileInput was left and the import of Choice was missing.**

**If someone who comes to the documentation as an example to use this option, and the same, is not used to understanding the error stacktrace that will get, this error can cause a certain dislike with the library and even generate a headache for the developer using it.**

```
import React from 'react';
import { Form, FileInput } from '@rocketseat/unform';

function App() {
  function handleSubmit(data) {}

  function handleProgress(progress, event) {}

  return (
    <Form onSubmit={handleSubmit}>
      <Choice name="fieldName" options={[
        { value: '1', label: 'One' },
        { value: '2', label: 'Two' }
      ]} multiple />

      <button type="submit">Send</button>
    </Form>
  );
}
```
Get this error: 
```
/index.js
  Line 11:  'Choice' is not defined  react/jsx-no-undef

Search for the keywords to learn more about each error.
```
This is the correct example: 

```
import React from 'react';
import { Form, Choice } from '@rocketseat/unform';

function App() {
  function handleSubmit(data) {}

  function handleProgress(progress, event) {}

  return (
    <Form onSubmit={handleSubmit}>
      <Choice name="fieldName" options={[
        { value: '1', label: 'One' },
        { value: '2', label: 'Two' }
      ]} multiple />

      <button type="submit">Send</button>
    </Form>
  );
}
```

**Comment by jpdemagalhaes** [comment]
Hey @murilokaos thanks for pointing that out 😄 

Could you make a PR fixing this?

**Comment by jpedroschmitz** [comment]
Hey @murilokaos, how are you? 
We have updated the docs on #136 and #132. Thanks for pointing that out 💜
