### ISSUE TITLE
How does schema works when using custom field

### ISSUE THREAD

**Issue by ricardo85x** [Rocketseat/unform#130]
How does schema works when using custom field

the 'error' on userField does not seems to catch the validation message.

**Comment by diego3g** [comment]
Hello @ricardo85x, Unform released version 2.0 🎉

And now, validation is out of the box, so you need to install and import your own validation library and use it inside submit function.

All the input values are passed inside the data object to the submit function, so you can use them the way you prefer.

Check this guide: https://unform.dev/guides/validation
