### ISSUE TITLE
The resetForm() function don't work when Form is a component inside another component?

### ISSUE THREAD

**Issue by DeeSouza** [Rocketseat/unform#133]
**Description of bug**

The `resetForm()` function don't work when the Form from unForm is a component inside another component. Example below:

```
function handleSubmit(data, { resetForm }) {
	dispatch(createRequest(data));

        resetForm();
}
```

```
<FormMeet onSubmit={handleSubmit} />
```

And inside this component `FormMeet` have a `Form `of **unForm**.

**Screenshots**

![image](https://user-images.githubusercontent.com/12430887/65269731-28060480-daf0-11e9-8bf9-13b3fcc6fb64.png)

**Comment by jpedroschmitz** [comment]
@DeeSouza, actually, it is not possible to have a form inside another form. It goes against [W3C specification](https://html.spec.whatwg.org/multipage/forms.html#the-form-element).

> **Content model:**
> Flow content, but with no form element descendants.

As it is not a problem with unform itself, I am closing this issue 💜

**Comment by DeeSouza** [comment]
I don't undestand very well what you say about this.
I don't have `form` inside of another `form`. Don't said this.

I said that o `Form` of `unForm` is inside of another component and not that a `Form` is inside of another `Form.`
