### ISSUE TITLE
Submit outside form element

### ISSUE THREAD

**Issue by e3duardo** [Rocketseat/unform#134]
Hi! 
I want to put a submit button outside a form element, what the better way to achieve that?
I tried use ref in the form with no success.

**Comment by lukemorales** [comment]
@e3duardo you can do that with the properties HTML5 provides to forms, no extra JS needed to do this: you simply set an id to your form, and reference that form on your button like this:

```html
<Form id="yourFormID">
	<Input (...) />
</Form>

<button type="submit" form="yourFormID"> Send </button>
```

**Comment by jpdemagalhaes** [comment]
I'll be closing this @e3duardo as it seems that @lukemorales proposed a solution!

But feel free to reopen this issue in case you feel like we missed something ❤️
