### ISSUE TITLE
Environment missing

### ISSUE THREAD

**Issue by JonathanVeg** [Rocketseat/unform#147]
**Description of issue**

I forked the project for creating a small update (the ability to add an element inside each `Choice` block of `input` and `label`. But I can not run the tests and the documentation does not give me all information needed to setup everything needed to do that.

**Comment by diego3g** [comment]
Hello @JonathanVeg, i'll check that.

As we released Unform 2.0, you can now just fork and clone the repo and inside the project folder just run `yarn` so you can install all the workspace dependencies.

After that, you can run `yarn test` to run all the tests.

Keep in mind that Unform now uses monorepo structure, so all of the code is splitted between packages inside `packages` directory.

If you need any further help, please reopen the issue :)
