### ISSUE TITLE
Reinitialize form data

### ISSUE THREAD

**Issue by zaguiini** [Rocketseat/unform#149]
**What would you like to be added**:

I'd like to have the possibility of restarting the form from outside the submit handler.

**Why is this needed**:

Because sometimes you want to reset or change the values of the form without submitting it.

**Additional context**

Formik already does that with the `enableReinitialize` prop that detects changes on `initialValues` (our `initialData`). We could make something like that. One implementation idea is to have an effect that will watch for changes in `initialData` reference and update the form state and clear its errors. Looks neat :)

**Comment by diego3g** [comment]
Hello @zaguiini, unform released version 2.0 🎉

And now you can reset or set form data out of the submit handler.

Check this guide: https://unform.dev/recipes/accessing-form-ref
