### ISSUE TITLE
Problem to submit a form with a custom element

### ISSUE THREAD

**Issue by EduardoAraujoB** [Rocketseat/unform#152]
**Description of bug**

I think that the form has to be submitted, but i don't know if i'm forgetting something, so is it a problem of the uniform or i'm using it at the wrong way?

**To Reproduce**

1 - Create a form with unform and a custom element as a child
2 - Create a file input with the useField in the child component
3 - Try to submit it

**Expected behavior**

I think that the form has to be submitted, but i don't know if i'm forgetting something, so is it a problem of the uniform or i'm using it at the wrong way?

**Exception or Error**

<strong>Parent Component:</strong>
<pre><code>
import React from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Form, Input } from '@rocketseat/unform';

import { updateProfileRequest } from '~/store/modules/user/actions';

import AvatarInput from './AvatarInput';

import { Container } from './styles';

export default function Profile() {
  const dispatch = useDispatch();
  const profile = useSelector(state => state.user.profile);

  function handleSubmit(data) {
    dispatch(updateProfileRequest(data));
  }
</code></pre>
```
return (
    <Container>
      <Form initialData={profile} onSubmit={handleSubmit}>
        <AvatarInput name="avatar_id" />

        <Input name="name" placeholder="Nome completo" />
        <Input name="email" placeholder="Seu endereço de e-mail" />

        <hr />

        <Input
          type="password"
          name="oldPassword"
          placeholder="Sua senha atual"
        />
        <Input type="password" name="password" placeholder="Nova senha" />
        <Input
          type="password"
          name="confirmPassword"
          placeholder="Confirmação de senha"
        />

        <button type="submit">Atualizar perfil</button>
      </Form>
      <button>Sair do GoBarber</button>
    </Container>
  );
}
```

<strong>Child Component:</strong>
<pre><code>
import React, { useState, useRef, useEffect } from 'react';
import { useField } from '@rocketseat/unform';
import api from '~/services/api';

import { Container } from './styles';

export default function AvatarInput() {
  const { fieldName, registerField, defaultValue } = useField('avatar');

  const [file, setFile] = useState(defaultValue && defaultValue.id);
  const [preview, setPreview] = useState(defaultValue && defaultValue.url);

  const ref = useRef();

  useEffect(() => {
    if (ref.current) {
      registerField({
        name: fieldName,
        ref: ref.current,
        data: 'dataset.file',
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ref.current, fieldName]);

  async function handleChange(e) {
    const data = new FormData();

    data.append('file', e.target.files[0]);

    const response = await api.post('files', data);

    const { id, url } = response.data;

    setFile(id);
    setPreview(url);
  }
</code></pre>
```
return (
    <Container>
      <label htmlFor={fieldName}>
        <img
          src={
            preview || 'https://api.adorable.io/avatars/50/abott@adorable.png'
          }
          alt=""
        />

        <input
          type="file"
          id="avatar"
          accept="image/*"
          data-file={file}
          onChange={handleChange}
          ref={ref}
        />
      </label>
    </Container>
  );
}
```
**Screenshots**

![bug2](https://user-images.githubusercontent.com/42449213/67314356-ea274200-f4da-11e9-99ae-9b97af9f725d.png)

**Environment:**

 - OS: Windows 10
 - Browser Chrome
 - React Version:  16.10.2
 - Unform Version: 1.6.1

**Comment by danieldfc** [comment]
I had a problem similar to the guy, but the button is not doing the submit action on the form, I don't understand!

![image](https://user-images.githubusercontent.com/33139541/79735237-5807c700-82ce-11ea-8fd3-8840562b6cf2.png)

**Comment by diego3g** [comment]
@danieldfc It looks like you're not using Unform at all as you're saving the input value inside a component state. Unform doesn't need that. Also, you're passing `schema` as a Form property but we dropped this since Unform 2.0 was launched.

You can take a look at the migration guide: https://unform.dev/migration-guide

**Comment by danieldfc** [comment]
@diego3g  I was not aware of this new update, which is why I had these problems. However, thanks for showing me how I can update to this new version of unform. :rocket:
