### ISSUE TITLE
Input not update value when changed

### ISSUE THREAD

**Issue by Davidiasdesousa** [Rocketseat/unform#157]
When I click on an input and make a change, the value is fixed to the 'value' attribute.
 
**To Reproduce**
 
https://prnt.sc/pycd6x

https://prnt.sc/pycdcl

 
**Environment:**

 - OS:  Windows 10 
 - Browser Chrome Versão 78.0.3904.97 (Versão oficial) 64 bits)

**Comment by sidroniolima** [comment]
Happening with me too. The values of component update as the input value but the screen is not rendered with the new value.

**Comment by diego3g** [comment]
We'll be covering this in Unform 2.0 tagged by branch 2.0. In the next release you'll have a method called `setData` and `setFieldValue` to set manually a value to any field inside the form.

We'll probably have Unform 2.0 in a couple weeks.

**Comment by diego3g** [comment]
Unform released 2.0 🎉

Now you can set an input value manually using the new form reference API.

Check this out: https://unform.dev/guides/get-set-field-value
