### ISSUE TITLE
Integration with Material-UI

### ISSUE THREAD

**Issue by Lekha30** [Rocketseat/unform#160]
**What would you like to be added**:

Is there an idea to integrate with MAterial-UI library

**Why is this needed**:

Since MAterial-UI is now widely used, it would be great to integrate this library with material-ui.
**Is your enhancement request related to a problem? Please describe.**

**Additional context**

**Comment by vinniimiranda** [comment]
I need this too

**Comment by italoiz** [comment]
There is an implementation in the previous version of Unform: [unform-material-ui](https://github.com/italoiz/unform-material-ui). Created by me, I am working on a new implementation for this new version.

**Comment by diego3g** [comment]
@italoiz Great to hear that, after you finish let us know!

**Comment by italoiz** [comment]
@diego3g Do you think it is a good idea to try to put it in the `@unform/material-ui` package?

**Comment by diego3g** [comment]
@italoiz As probably we'll have a lot of integrations maybe we should maintain in separate orgs so it does no depend on us to invite people to NPM org.

I think `unform-material-ui` is a good name 🤘🏻

**Comment by italoiz** [comment]
In parallel, I am also creating an implementation for [ant.design](https://ant.design). Soon he will be in the community.

**Comment by lexarno** [comment]
Guys, is there any forecast to launch this implementation? I've been using https://material-ui.com/ a lot and I really liked the new version of Unform.

**Comment by lucianocorreia** [comment]
I'm developing a new Application and I'm testing Ant Design and Material-ui. Any prediction of when the integration with these Libs will come out?

**Comment by italoiz** [comment]
@lexarno @lucianocorreia I have a lot of work here, but it is likely that I will release a version in two weeks.

**Comment by leonardorpr** [comment]
Hi guys! 
First sorry for any mistake in my english.

About Material UI integration, is it really necessary? Input components like: `TextField`, `OutlinedInput` and others has a prop called `inputRef`, pass your `inputRef` on that prop and problem solved (:

**Comment by wmattei** [comment]
@leonardorpr, i agree! @italoiz what exactly is this lib you are working in about?

**Comment by maxleon52** [comment]
I'm sorry for my English.

@diego3g  is there any incompatibility of unForm with the material-ui? Because unForm works with the INPUT field and Material-ui with TEXTFIELD.

**Comment by wmattei** [comment]
@maxleon52 TextField is a component that uses the natvia `input` element

**Comment by italoiz** [comment]
@leonardorpr @wmattei 

Take the following documentation as an example: [Basic Form - Unform](https://unform.dev/guides/basic-form)

Based on the documentation above, it would be necessary that every time we wanted to use some kind of input, we would register the same. Now imagine in large forms, how laborious it would be.

The library in which I am working leaves aside some of this concern to focus on what is important, the creation of the form. Instead of creating forms based on the above documentation, we would only concern ourselves with creating forms as follows:

```jsx
import { Form } from '@unform/web';
import { TextField } from 'unform-material-ui';

export default function App(){
  return (
    <Form>
      <TextField name="input_name" />
    </Form>
  )
}
```

We only care about assigning a name to the field instead of having to use the entire Unform API. But behind the scenes, the library brings the features of Material UI / Antd for example, along with the features and ease of Unform.

I hope I helped you understand the need for the library. Strong hug!

**Comment by wmattei** [comment]
Got it!, Yeah it makes sense now, basically you will remove the requirement of creating custom Inputs, right?

**Comment by italoiz** [comment]
@diego3g 

I just released a new version that supports Unform in its version 2.0. Take a look: https://github.com/italoiz/unform-community-packages/tree/master/packages/material-ui

For those who were waiting ... It doesn't have all the components but soon it will have more news.

@vinniimiranda @lexarno @lucianocorreia

**Comment by w1redl4in** [comment]
@italoiz are you still working on a Antd integration?

**Comment by italoiz** [comment]
@w1redl4in Yes, I'm working. You can follow it [here](https://github.com/italoiz/unform-community-packages), this [branch](https://github.com/italoiz/unform-community-packages/tree/feat/antd-support).

**Comment by uandersonmbc** [comment]
> I'm sorry for my English.
> 
> @diego3g is there any incompatibility of unForm with the material-ui? Because unForm works with the INPUT field and Material-ui with TEXTFIELD.

As @leonardorpr  said, just change the ref to inputRef, and your problem is solved.

**Comment by diego3g** [comment]
Closing this issue, please @italoiz keep us informed about updates in this integration.
