### ISSUE TITLE
Provide Yup schema information about the field to components

### ISSUE THREAD

**Issue by thiagozf** [Rocketseat/unform#162]
**What would you like to be added**:

Provide Yup field information to component.

**Why is this needed**:

Since we are able to define a Yup schema in the `Form` component, it would be nice to use that information not only for validations, but also to render my input components. For example, if I mark a field as [required](https://github.com/jquense/yup#mixedrequiredmessage-string--function-schema) in the schema, the component could use that data to render a required indicator. Same applies to other things, ie. [label](https://github.com/jquense/yup#mixedlabellabel-string-schema). 

**Is your enhancement request related to a problem? Please describe.**

I don't like to pass props like `label`, `required` and `maxLength` to form components if I already have a schema definition that describes the expected behaviour of the Form.

**Additional context**

Also had the same issue with [Formik](https://github.com/jaredpalmer/formik):

- jaredpalmer/formik#1241
- jaredpalmer/formik#712

**Comment by thiagozf** [comment]
Just did a quick implementation at d22d3df46a8417fe6298f88d1b4b8de71ca0f0df. I can do a final PR if you guys point me directions on how you'd expect this feature to work.

**Comment by diego3g** [comment]
Unform released version 2.0 🎉

And now, all of the validation is out of the box, so Unform does not includes a schema property anymore, you can choose your favorite validation library and use it inside the submit handler.

Also, you can reuse the same validation schema inside your inputs passing it with a context in React.

Please let me know if you need any further help.
