### ISSUE TITLE
Each child in a list should have a unique "key" prop. 

### ISSUE THREAD

**Issue by carlosrodrigues94** [Rocketseat/unform#163]
i´m having this problem when i try to use `<Select /> `
i tried put the key in object ... ex: 
 ``
`const test = [ { id: 1, name: Carlos, key: 01 }, {id: 2,  name: Maria, key: 02 } ] `
 doesn´t work

tried put in Select 

`<Select key={test.id} options={test} /> `
 doesn´t work

what i have to do to solve this problem?"`

**Comment by diego3g** [comment]
Hey @carlosrodrigues94, you good?

Unform released version 2.0 🎉

Now we do not include any input component inside the library.

But i highly recommend you to use the `react-select` instead of using the HTML Select element.

Check this guide: https://unform.dev/third-party/react-select
