### ISSUE TITLE
AutoFocus on Reset Form

### ISSUE THREAD

**Issue by lipex360x** [Rocketseat/unform#168]
**What would you like to be added**:
Autofocus on text input when the form is reset

**Why is this needed**:
After resetting the form, I need a specific text entry to be focused

So that a user does not need to click on the input text every time the form is reset

**Is your enhancement request related to a problem? Please describe.**
It isn't a problem

**Additional context**
Example: login page

**Comment by thaydds** [comment]
hi @lipex360x ,

i modified the resetForm function to accept a second param called focusedElement, so you can pass the element that need to be focused after the reset statement.
as you can see:
![image](https://user-images.githubusercontent.com/4451937/73199489-b2e8b280-4113-11ea-8776-4fd1bac284a6.png)

i create a example to show how it works:
![deepin-screen-recorder_Select area_20200127144909](https://user-images.githubusercontent.com/4451937/73199850-62be2000-4114-11ea-8952-641f8d69ca10.gif)


but, i need some help too.
i dont know how to fix: 

> Property 'name' does not exist on type 'HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | HTMLInputElement[] | null[]'.
  Property 'name' does not exist on type 'HTMLInputElement[]'.ts(2339)

do you have any idea?

**Comment by diego3g** [comment]
Hello guys!

We've released Unform 2.0 🎉

With this release, you can access the field reference and `.focus` it easily using the `getFieldRef` function provided by unform.

You can follow the migration guide inside the docs and [this guide](https://unform.dev/recipes/accessing-field-ref) to check the `getFieldRef` function.

I'll close this issue for now as we moved to a totally brand new version of unform, but feel free to reopen it or create new ones if you have any problem.
