### ISSUE TITLE
[RFC] Reset form data

### ISSUE THREAD

**Issue by diego3g** [Rocketseat/unform#17]
There are many ways that we can provide for user to reset form data and clear all input fields, so the main discussion points here are:

- Should we reset form after submit automatically?
- How edit cases would work? Clear data or return to initial data?

My suggestion is to offer an helper inside `onSubmit` so user can reset data after submit like this:

```js
function handleSubmit(data, { reset }) {
  // user function to deal with data
  reset();
}
```

Issue related: #16

**Comment by jpdemagalhaes** [comment]
I was thinking something like `clearOnSubmit` prop inside `<Form>`, but I like yours better.

> Should we reset form after submit automatically?

Personally I think that the form should not reset automatically. We should either provide a prop like `clearOnSubmit` or a helper like you suggested.

> How edit cases would work? Clear data or return to initial data?

Perhaps we should offer the option to pass the data inside `reset()`? So if you need to return the state to its initial data you'd do `reset(initialData)`, if empty, clears the inputs.

@diego3g could you provide an example of a situation where it might be needed to reset the inputs to its initial data (assuming they're populated, of course).

**Comment by diego3g** [comment]
@jpdemagalhaes Great!

The example would be something like an reset button (is it still used) inside the form near the submit. But i really think it's something we should not implement.

**Comment by jpdemagalhaes** [comment]
Hmm, clearing a form with a button is possible with `<input type="reset" />`. It creates a button that when pressed clears all the inputs of the form, and when you have `defaultValue`, it returns to that state.

Which got me thinking. I feel like the only thing we should provide is `clearOnSubmit` prop, or like you suggested, a helper, which would be useful to reset the fields automatically after a submit. What do you think @diego3g ?

**Comment by diego3g** [comment]
@jpdemagalhaes Great, forgot about that! So let's keep with the helper idea, i think it's more readable and extendable as we are able to send params and have more helpers.

**Comment by italoiz** [comment]
I was making an implementation to reset the data after sending, passing a `reset` property that could be three types of values, they are:

1. string `on-success`. _Only when the submission was successful._
2. string `on-error`. _Only when an error occurs on the form._
3. string `on-submit`. _In both cases above._

_I stopped the feature when I saw this discussion._

My idea was following the logic of @jpdemagalhaes, but I was having trouble testing the call of a parameter that could be passed, the `onReset`. For some reason Jest could not identify.

Example:
```jsx
<Form onReset={handleReset} reset="on-success" ... />
```

I had thought of a solution similar to that of @diego3g, I did not continue to think it was not so good when the other alternative. But seeing this discourse, realize that it is the best way.

For this reason, I believe that @diego3g solution is good. I would like to know if I can send a PR for this feature, if it is not already in development.

**Comment by diego3g** [comment]
@italoiz Great! We are looking into it. I've got the same problem in Jest but i managed to do it, but got some other problems with custom and select element. I got only input and textarea working for now. I'll probably send one PR until the weekend.
