### ISSUE TITLE
Add prop to parse values when submitting the form

### ISSUE THREAD

**Issue by caioedut** [Rocketseat/unform#182]
**What would you like to be added**:

A simple and automatic way to parse values when submitting the form.

**Why is this needed**:

To make the "handleSubmit" code less verbose

**Additional context**

Eg.: if I want a intbool checkbox, the parse looks like: 
```javascript
<Input  valueParse={(value, inputRef) => +inputRef.current.checked} />
```
Symbol (+) convert bool to int

**Comment by Matgsan** [comment]
Aren't you able to do that already? You can create your own input component.

**Comment by caioedut** [comment]
The intention is to make it simpler, using a component already created, but modify the value in the handleSubmit to, for example, remove masks.

**Comment by diego3g** [comment]
@caioedut As you can create your own input i think it's better if you create a `Checkbox` component, and you can use the `getValue` function inside `registerField` to parse the value before it's returned to the submit handler.

**Comment by MateusSoares895** [comment]
I will try implement this feature

**Comment by diego3g** [comment]
As we didn't have any updates on this, i'll close this issue for now but feel free to reopen it if the problem persists.
