### ISSUE TITLE
RadioButton funcionality

### ISSUE THREAD

**Issue by filipecoelho** [Rocketseat/unform#184]
How would RadioButton and OptionButton look?
Is it possible to implement this feature?

**Comment by diego3g** [comment]
Hi @filipecoelho, i did an example implementation of Radio Buttons with Unform.

https://codesandbox.io/s/heuristic-haslett-58hhy?fontsize=14&hidenavigation=1&theme=dark

Let me know if it helped you.

**Comment by rafaelqw** [comment]
Hi @diego3g ,

I used this sample code and it was perfect, but I had some doubts ...

As it would be to set a default value at startup and also when something is returned from the API, I tried using the setData and it didn't work.

Thankful.

**Comment by diego3g** [comment]
Hello, @rafaelqw!

I updated the example with support for `defaultValue` and manual `setData`, can you take a look and share your thoughts?

https://codesandbox.io/s/heuristic-haslett-58hhy?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark

**Comment by rafaelqw** [comment]
Wonderful, it worked! Thank you!

**Comment by sJonatas** [comment]
> Hi @filipecoelho, i did an example implementation of Radio Buttons with Unform.
> 
> https://codesandbox.io/s/heuristic-haslett-58hhy?fontsize=14&hidenavigation=1&theme=dark
> 
> Let me know if it helped you.

Works perfectly
nice job and thanks :D
