### ISSUE TITLE
New example in the docs with the lib "benhurott/react-native-masked-text" or even support to it

### ISSUE THREAD

**Issue by AllyssonAlas** [Rocketseat/unform#186]
**What would I like to be added?**
Searching through the docs I didn't find any example with some lib that has input mask and integration with React Native.

**Why is this needed?**
Since **unform** has integration with RN, is relevant to it examples with some libs focused in RN or even support or integration.

**Is your enhancement request related to a problem? Please describe.**
In RN isn't easy as ReactJS (web) to make masks for inputs, this lib in my opinion provides the best solution to the problem.

**Comment by Matgsan** [comment]
@AllyssonAlas You can just create a custom Input for unform normally and when using that lib pass the prop `customTextInput={YOUR_INPUT}`. Replace the YOUR_INPUT with the import for your unform Input component.

**Comment by AllyssonAlas** [comment]
> @AllyssonAlas You can just create a custom Input for unform normally and when using that lib pass the prop `customTextInput={YOUR_INPUT}`. Replace the YOUR_INPUT with the import for your unform Input component.

Actually I tried, but without  success. I discovered that the common Input and the TextInputMask (the input of the lib) are different in reference, and even the methods inside to set setNativeProps are different too. I'm afraid that you'll need more than that prop to make that lib work with unform

**Comment by Rise95** [comment]
Bom dia, uma dica resolvi a questão da mascara usando o mesmo exemplo que tem na documentação para web, porem no react native alterei a lib para essa aqui https://github.com/react-native-community/react-native-text-input-mask

**Comment by diego3g** [comment]
Hi @AllyssonAlas, have you tried to implement this with this library instead? https://github.com/react-native-community/react-native-text-input-mask

I think it's a better approach since it's from the react-native-community.

**Comment by AllyssonAlas** [comment]
> Hi @AllyssonAlas, have you tried to implement this with this library instead? https://github.com/react-native-community/react-native-text-input-mask
> 
> I think it's a better approach since it's from the react-native-community.

I chose this lib because it is entirely in Javascript, no need of further steps to install besides the npm install.

**Comment by AllyssonAlas** [comment]
I managed to find a solution, don't know if it is the best solution but it worked and it relies on the unform purpose, no state. 

**Based on the common input provided by the unform docs for React Native**


`import {MaskService} from 'react-native-masked-text'

<Input
	keyboardType={'numeric'}
	onChangeText={text => {
		const formatted = MaskService.toMask('datetime', text, {
			format: 'DD/MM/YYYY',
		})
		formRef.current.setFieldValue('birthDate', formatted)
	}}
	label={'Data de Nascimento:'}
	name={'birthDate'}
	maxLength={10}
/>`

Instead of using the TextInputMask provided by the lib, use its MaskService and set the field with setFieldValue function of unform, plus the prop maxLength is needed because without it the input field captures one additional char becoming like this _09/09/19999_ (for dates, in an example). 

Would be nice to see this example or a better one using libs like this one for masks in the docs. I'm closing this issue for now
