### ISSUE TITLE
useEffect not include in live example

### ISSUE THREAD

**Issue by JulioVMelo** [Rocketseat/unform#187]
Is necessary import useEffect in [ simple input documentation]( https://unform.dev/recipes/simple-input) live example

**Comment by jpedroschmitz** [comment]
Hey @JulioVMelo, thanks for pointing this up. Could you please open a PR for us, fixing it? 💜

**Comment by JulioVMelo** [comment]
@jpedroschmitz   :+1:

**Comment by JulioVMelo** [comment]
#194
