### ISSUE TITLE
setData trigger setValue

### ISSUE THREAD

**Issue by felipecoders** [Rocketseat/unform#193]
**What would you like to be added**:
When we use `formRef.current.setData({})` it should trigger `registerRef.setValue`.

**Why is this needed**:
 To handler the values in custom inputs models before to update.

**Is your enhancement request related to a problem? Please describe.**
To get setData value today i'm using `useEffect(() =>{}, [defaultValue])`, but this method cause `Warning: Maximum update depth exceeded.`.

**Additional context**

**Register.tsx**
```tsx
const Register: React.FC = () => {
  const formRef = useRef<FormHandles>(null);

  useEffect(() => {
    formRef.current?.setData({ screen: { id: 1, name: 'temp name' } });
  });

  return (
    <Form ref={formRef}>
      <Card name="screen" />
    </Form>
  )
}
```

**Card.tsx**
```tsx
const Card: React.FC<Props> = ({ name }) => {
  const cardRef = useRef<HTMLDivElement>(null);
  const { defaultValue = {}, error, fieldName, registerField } = useField(name);
  const [value, setValue] = useState(defaultValue);

  //#region to update value when 'setData' has be used
  useEffect(() => {
    setValue(defaultValue);
  }, [defaultValue]);
  //#endregion

  useEffect(() => {
    registerField({
      ref: cardRef.current,
      name: fieldName,
      path: '',
      setValue(ref: any, value: any) {
        setValue(value);
        console.tron.log({ ref, value });
      },
      getValue(ref: any) {
        return value;
      },
      clearValue() {
        setValue({})
      }
    });
  }, [fieldName, registerField, value]);

  return (
    <Container ref={cardRef}>
      <div>{value.id}</div>
      <div>{value.name}</div>
    </Container>
  );
};
```

**Comment by diego3g** [comment]
Hi @felipecoders, you left your `useEffect` without any dependencies, so try to use it like this:
```js
useEffect(() => {
  formRef.current?.setData({ screen: { id: 1, name: 'temp name' } });
}. []);
```
So it will run only once.

**Comment by felipecoders** [comment]
Hi @diego3g , but when we have a component to handler subpaths, dosen't trigger o setValue. Ex:

```ts
useEffect(() => {
  formRef.current?.setData({ screen: {
    id: 1,
    name: 'temp name',
    layout: {
      id: 1,
      name: 'another name'
    }
  } });
}. []);
```

#### component
```tsx
const { defaultValue = {}, error, fieldName, registerField } = useField('layout');

useEffect(() => {
    registerField({
      ref: cardRef.current,
      name: fieldName,
      path: '',
      setValue(ref: any, value: any) {
        setValue(value);
        console.tron.log({ ref, value });
      },
      getValue(ref: any) {
        return value;
      },
      clearValue() {
        setValue({})
      }
    });
  }, [fieldName, registerField, value]);
```

It's case, `setValue` dosen't trigger by `setData`.

**Comment by jessicabetonico** [comment]
I have the same problem with array data, setFieldValue works, but setData not.

**Comment by diego3g** [comment]
@jessicabetonico @felipecoders Can someone please provide a Code Sandbox demo with the problem? 

I'm trying to reproduce this problem, but i can't.

Thanks.

**Comment by felipecoders** [comment]
https://codesandbox.io/s/lingering-wildflower-qxn2u

**Comment by diego3g** [comment]
@felipecoders Now i got it, you're trying to set the value of the input as an object? So you want to set the value of `screen` as:
```
{
  id: 1,
  name: "temp name",
  layout: {
    id: 1,
    name: "another name"
  }
}
```
Is it right? 

Unform runs through this object and it's probably trying to find an input named `screen.id`, another `screen.name`, another `screen.layout.id` and `screen.layout.name`.

So, Unform does not comprehends that you're setting an object as the `screen` value.

I'm trying to think about an easy way for us to implement this, if you have any thoughts about that it'll be great!

**Comment by dmcardoso** [comment]
Same problem on input files and react-select
