### ISSUE TITLE
React sematic-ui library

### ISSUE THREAD

**Issue by AdilsonLopesDev** [Rocketseat/unform#199]
Hello Devs, I hope you are all well.
how could i use unForm with the react sematic-ui library?
I would like to be able to use unform with this library.
Someone could help with that.

**Comment by diego3g** [comment]
Hello @AdilsonLopesDev, how are you?

I made a simple Code Sandbox with Semantic UI Form and Input as an example.

https://codesandbox.io/s/objective-goodall-77swi?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark

Let me know if it helps you.

**Comment by AdilsonLopesDev** [comment]
I'm very well.
Thank you very much, it helped me a lot, you are the best.
