### ISSUE TITLE
I can't access a field ref on useEffect

### ISSUE THREAD

**Issue by claudiohilario** [Rocketseat/unform#200]
**Description of bug**
I can't access a field ref on useEffect in parent component (similar to `componentDidMount`).
But if i use `setTimeout` works :D 

```
setTimeout(() => {
    refForm.current.getFieldRef("email").focus();
}, 0);
```
is supposed?

**To Reproduce**
```js import React, { useEffect, useRef } from "react";
import { Form } from "@unform/web";
import Input from "./components/Input";

export default function App() {
  const refForm = useRef(null);
  function handleSubmit(data) {
    console.log(data);
  }

  useEffect(() => {
    refForm.current.getFieldRef("email").focus();
  }, []);

  return (
    <Form ref={refForm} onSubmit={handleSubmit}>
      <Input label="E-mail" name="email" />
      <button>Enviar</button>
    </Form>
  );
}
 ```

Complete example: https://codesandbox.io/s/reffield-xyo92

**Exception or Error**

<pre><code>
TypeError
refForm.current.getFieldRef(...).focus is not a function
</code></pre>

**Comment by diego3g** [comment]
@claudiohilario The `formRef` is not exposed since the beginning of the component render, so, generally you'll have access to it after the component already rendered.

Can you try using `autofocus` property on the input?

```html
<Input label="E-mail" name="email" autofocus />
```

**Comment by claudiohilario** [comment]
@diego3g Yes, it works, but if I want to control the child components, I need to use props and status?

I thought that after the "componentDidMount", all the ref methods would be available. (theoretically) right?

I thought it would be good to report 😄

**Comment by diego3g** [comment]
The first `useEffect` runs in parallel with component render, so for the first time it'll probably not be available. You can use the `setTimeout` or you can try using the `useLayoutEffect` instead of `useEffect`.

**Comment by diego3g** [comment]
Closing this issue as there were no interactions for some days. Feel free to reopen it 💜

**Comment by eddyrusso** [comment]
`formRef.current.getFieldRef("name").current.focus();`
