### ISSUE TITLE
Fix react-input-mask setValue doc

### ISSUE THREAD

**Issue by leonardobrito** [Rocketseat/unform#202]
**Description of issue**
Currently, the [reaction-input-mask example in the documentation](https://unform.dev/examples/react-input-mask) does not define a value in `ref.setInputValue('');`.

**Usage example**

To fix just change to:

```js 
     setValue(ref: any, value: string) {
        ref.setInputValue(value);
      },
```

**Comment by diego3g** [comment]
Fixed in #211
