### ISSUE TITLE
How create my inputs

### ISSUE THREAD

**Issue by albertoammar** [Rocketseat/unform#206]
Documentation is empty:
https://unform.dev/recipes/creating-your-own-inputs

I would like to create my custom inputs, but I don't know where to start.

Example:

```
const ButtonsGroup = ({ buttons, name, onChange }) => {
    return (
        <div className="btn-group">
            {buttons &&
                buttons.map(i => (
                    <div
                        key={i.name}
                        className={\`btn ${selected == i.value && 'active'}\`}
                        onClick={() => select(i.value)}
                    >
                        {i.name}
                    </div>
                ))}
        </div>
    );
};
```

**Comment by albertoammar** [comment]
someone?

**Comment by felipedssantos** [comment]
I Have same problem, this part on docs are empty

**Comment by diego3g** [comment]
Hello @albertoammar and @felipedssantos, we're still working on this part of docs.

You can take a look at some examples we have implementing React Select, React DatePicker and other libraries.

Unform exposes an `useField` hook that you need to call inside your custom input:

I made an example trying to implement what you mentioned in this issue, please take a look and let me know if it's clearer to you: https://codesandbox.io/s/optimistic-tdd-iprcz

The main points to keep in mind:

1. We need to use an `useRef` hook so we can access the final value directly, without needing to access the component state;
2. As buttons are not native inputs we need to store the value somehow we can access it after the submit, so i'm storing it with `data-value={value}` on the `div` outside the ButtonInput component;
3. Also, as buttons are not native inputs, we need to save the input state with an `useState` as there is no native `value` property inside them.

**Comment by albertoammar** [comment]
Nice @diego3g , it's work for me!

**Comment by diego3g** [comment]
Closing this issue for now, feel free to reopen it if it's necessary! :)
