### ISSUE TITLE
How to add options in a select element?

### ISSUE THREAD

**Issue by Sutolix** [Rocketseat/unform#207]
I read the documentation but only found the part about React Selector. I managed to add the element on the screen but I don't know where to add the options.

**Comment by leonardobrito** [comment]
@Sutolix take a look at this link [https://codesandbox.io/s/throbbing-firefly-cob4s](https://codesandbox.io/s/throbbing-firefly-cob4s), maybe it can help you. 🤙

**Comment by Sutolix** [comment]
Oh, nice. Thanks man
