### ISSUE TITLE
Why do you use local state?

### ISSUE THREAD

**Issue by kserjey** [Rocketseat/unform#208]
**What would you like to be added**:

Replace `useState` with `ref`

**Why is this needed**:

I have seen through your code and stated to wonder why don't use simply `ref` for _fields_?. As far as I understand, there is no need in `useState`, because nothing depends on it.

**Comment by diego3g** [comment]
@kserjey Can you send us an implementation through a Pull Request? I'd appreciate.

**Comment by kserjey** [comment]
I am working on a similar solution for complex forms at my work. I have taken your library as a basis. There are some ideas that I am experimenting on and when I come up with something, I will send you a Pull Request.

**Comment by diego3g** [comment]
Great to hear that @kserjey, we're always looking for new contributors and maintainers if it's your desire! 👍
