### ISSUE TITLE
Add function to clear the error message when typing or focus in the input

### ISSUE THREAD

**Issue by ZeFelix** [Rocketseat/unform#216]
**What would you like to be added**:
Add a function inside the `Uniform Field` where I can clear the message

**Why is this needed**:

User usability issues when entering a correct entry

**Is your enhancement request related to a problem? Please describe.**

This problem occurs when I have an input where the error message exists, but I want the error message for that input to be erased when typing or focusing on the input

**Additional context**

**Comment by diego3g** [comment]
Working on that!

**Comment by diego3g** [comment]
Fixed in #223.
