### ISSUE TITLE
Empty fields on submit running basic example with react-native 0.62.2

### ISSUE THREAD

**Issue by romulotorres** [Rocketseat/unform#220]
**Description of bug**
On submit form, usind react-native 0.62.2, all fields stay empty. 

**To Reproduce**

**Expected behavior**
Fields filled with inserted data.

**Exception or Error**

No error or exception to show

**Screenshots**

**Environment:**
Using a real device android MotoE 5, Android version: 8.0.0
Node: v12.16.2
Npm: 6.14.4
Flipper active

**Additional context**

Libs on package.json
"dependencies": {
    "@unform/core": "^2.0.0",
    "@unform/mobile": "^2.0.0",
    "react": "16.11.0",
    "react-native": "0.62.2"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "babel-jest": "^25.3.0",
    "eslint": "^6.8.0",
    "jest": "^25.3.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },

**Comment by diego3g** [comment]
I'll update the docs this week, but for now look at this issue #215
