### ISSUE TITLE
Bug on setData and maybe on getData

### ISSUE THREAD

**Issue by Vini-Dev** [Rocketseat/unform#222]
### Description of Bug
When i try execute the method setData on componentMount "useEffect(() => {},[])", the method not working.

### Follow the tests I did:

**Without async**
```js
useEffect(() => {
    console.log('Ref', formRef.current); // Output: {getFieldValue: ƒ, setFieldValue: ƒ, …}
    const setData = () => {
      formRef.current.setData(INITIAL_DATA);
      const data = formRef.current.getData();
      console.log(data);  // Output: {}
    };

    setData();
  }, [formRef]);
```

**With async**
```js
useEffect(() => {
    console.log('Ref', formRef.current); // Output: {getFieldValue: ƒ, setFieldValue: ƒ, …}
    const setData = async () => {
      await formRef.current.setData(INITIAL_DATA);
      const data = formRef.current.getData();
      console.log(data);  // Output: {name: "", email: "", phone: ""}
    };

    setData();
  }, [formRef]);
```
**It works 🤯...**
```js
useEffect(() => {
    console.log('Ref', formRef.current); // Output: {getFieldValue: ƒ, setFieldValue: ƒ, …}
    const setData = async () => {
      await formRef.current.getData();
      formRef.current.setData(INITIAL_DATA);
      const data = formRef.current.getData();
      console.log(data);  // Output: {name: "Example", email: "example@example.com, phone: "(00) 0000-0000"}
    };

    setData();
  }, [formRef]);
```

_**Note:** I didn't use the "initialData" property, because my form has a step by step and, in some parts, has state._

**Comment by carlosallexandre** [comment]
Hey @Vini-Dev, everything okay with u?

I was trying reproduce this bug [here on codesandbox](https://codesandbox.io/s/unform-issue222-toozi) without success.

The only difference is that i check **formRef.current** is truthy before **getData** and **setData** like shown below:
```js
useEffect(() => {
    console.log("Ref", formRef.current);

    const setData = () => {
      if (formRef.current) {
        formRef.current.setData(INITIAL_DATA);
        const data = formRef.current.getData();
        console.log(data);
      }
    };

    setData();
  }, [formRef]);
```
Keep us updated if it still happens.

**Comment by Vini-Dev** [comment]
I am solved my bug when I used "setValue" in my input components, I learned that just the reference path does not solve the whole problem. But, thanks for your comment!

Like this example: [https://unform.dev/examples/react-input-mask](https://unform.dev/examples/react-input-mask)
