### ISSUE TITLE
How to use react-select with typescript?

### ISSUE THREAD

**Issue by AntonioEduardo1998** [Rocketseat/unform#226]
I'm using the code that is in the documentation of Unform to use the react-select with tsx extension but I have a few errors that I can't resolve for myself. It seems to me that they are typing errors.

```
import React, { useRef, useEffect } from "react";
import ReactSelect, {
  OptionTypeBase,
  Props as SelectProps,
} from "react-select";
import { useField } from "@unform/core";

interface Props extends SelectProps<OptionTypeBase> {
  name: string;
}

const Select: React.FC<Props> = ({ name, ...rest }) => {
  const selectRef = useRef(null);
  const { fieldName, defaultValue, registerField, error } = useField(name);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: selectRef.current,
      path: "state.value",
      getValue: (ref: any) => {
        if (rest.isMulti) {
          if (!ref.state.value) {
            return [];
          }

          return ref.state.value.map((option: OptionTypeBase) => option.value);
        } else {
          if (!ref.state.value) {
            return "";
          }

          return ref.state.value.value;
        }
      },
    });
  }, [fieldName, registerField, rest.isMulti]);

  return (
    <ReactSelect
      defaultValue={defaultValue}
      ref={selectRef}
      classNamePrefix="react-select"
      {...rest}
    />
  );
};

export default Select;
```

Argument of type '{ name: string; ref: null; path: string; getValue: (ref: any) => any; }' is not assignable to parameter of type 'UnformField<any>'.
  Type '{ name: string; ref: null; path: string; getValue: (ref: any) => any; }' is not assignable to type 'FunctionUnformField<any>'.
    Types of property 'path' are incompatible.
      Type 'string' is not assignable to type 'undefined'.ts(2345)

**Comment by AntonioEduardo1998** [comment]
![image](https://user-images.githubusercontent.com/50385127/80253465-b70f6800-864f-11ea-9a77-7c4157bf1d6c.png)

**Comment by lcoalves** [comment]
I have same problem.

**Comment by deusdete-filho** [comment]
I have same problem.

**Comment by AntonioEduardo1998** [comment]
I resolved this issue by changing  the path to undefined.
![image](https://user-images.githubusercontent.com/50385127/80849492-bf3a4b00-8bed-11ea-977c-e0701822b0b2.png)
