### ISSUE TITLE
Problem on links inside documentation

### ISSUE THREAD

**Issue by filliperomero** [Rocketseat/unform#227]
**Description of issue**

All links that redirect to github are not working (the ones that has "Edit this page on GitHub"). The href is correct but gastby is putting "https://unform.dev/" in front of every link, so we end up on a 404 page.

Browser Informations
Browser: Chrome
Version: 80.0.3987.163 (Official Build) (64-bit)

**Usage example**
Enter the page: https://unform.dev/examples/file-input and click on "Edit this page on GitHub", you will be redirect to "https://unform.dev/github.com/Rocketseat/unform/tree/master/docs/src/docs/examples/file-input.mdx"

**Comment by diego3g** [comment]
Thanks, i'll fix that.

**Comment by thaydds** [comment]
> Thanks, i'll fix that.

@diego3g can i take this one? 
if you haven't done it yet, of course.

**Comment by diego3g** [comment]
@thaydds of course

**Comment by thaydds** [comment]
> @thaydds of course

hey @diego3g, correct me if i'm wrong but i think this issue belongs to another repository:
https://github.com/Rocketseat/gatsby-themes

i found the [demo](https://rocketdocs.netlify.app/) and we have the same error here too.
i'll check if i can fix.
tnks.

**Comment by diego3g** [comment]
@thaydds Did you manage to do that?

**Comment by jpedroschmitz** [comment]
Hey guys, thanks for reporting this problem 💜 

We fixed it on #270 🎉
