### ISSUE TITLE
getFieldRef not working

### ISSUE THREAD

**Issue by willianhf** [Rocketseat/unform#228]
**Description of bug**
`getFieldRef` method return `undefined` even the field exists.

**To Reproduce**
I've created a hook to wrap field register and an Input component
```js
function useRegisterField({ name, inputRef }) {
  const { fieldName, registerField, defaultValue = '', error } = useField(name);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: inputRef,
      path: 'value',
    });
  }, [fieldName, registerField, inputRef]);

  return { defaultValue, error };
}
```
```jsx
function InputMasked({ name, mask, ...props }) {
  const [currentValue, setCurrentValue] = useState('');

  const inputRef = useRef(null);

  const { defaultValue = '', error } = useRegisterField({
    name,
    inputRef: inputRef?.current?._inputElement
  });

  function handleTextChange(text) {
    setCurrentValue(text);

    inputRef.current._inputElement.value = text;
    inputRef.current._inputElement.setNativeProps({ text });
  }

  return (
      <TextInputMask
        ref={inputRef}
        type={mask}
        value={currentValue}
        onChangeText={handleTextChange}
        customTextInput={Styled.TextInput}
        customTextInputProps={{
          ...props,
          defaultValue,
          selectionColor: '#a6aeb6',
        }}
      />
  );
}
```
Then I tried to get it `ref`

```jsx
function handleSubmit() {
  const input = formRef.current.getFieldRef('cpf');
  console.log(input); // undefined
}

return (
  <Form ref={formRef} onSubmit={handleSubmit}>
    <InputMasked
      name="cpf"
      mask="cpf"
    />
  </Form>
);
```

**Expected behavior**
Return the input `ref`

**Environment:**
 - OS: MacOS Mojave
 - Simulator OS: iOS 12.0
 - Node: 10.16.3

**Comment by filliperomero** [comment]
Hello @willianhf, your problem is probably on the `ref: inputRef,` which receives the ref.current. 
In `InputMasked`, pass the ref like this:
```
const { defaultValue = '', error } = useRegisterField({
    name,
    inputRef: inputRef?.current
});
```
See that I removed `?._inputElement`. 
I did a quickly test here with codesandbox and now you should receive the ref correctly.

For future Issues, is nice to post the [codesandbox](https://codesandbox.io/s/), so we can test better since your code is missing some stuffs. 

By the way, I didn't test your `handleTextChange` function with this new change.

**Comment by willianhf** [comment]
Hi @filliperomero, I forgot to mention this issue is happening on React Native and I'm using `react-native-masked-text` to handle masked inputs. So in order to access input ref I need to pass the `_inputElement` property.

**Comment by filliperomero** [comment]
Oh, in that case some stuffs changed.
Can you post your code in Codesandbox? I think they have a template to React Native over there.
I can try to see again if there is a solution to your problem.

**Comment by willianhf** [comment]
@filliperomero I think it's an react-native related issue, here's the codesandbox.
https://codesandbox.io/s/unform-react-native-qbvq2

**Comment by willianhf** [comment]
I managed to solve the problem unregistering the field on `useEffect` cleanup.
