### ISSUE TITLE
Add commit linting

### ISSUE THREAD

**Issue by diego3g** [Rocketseat/unform#23]
Today, even with contribution guide, commits can have more than 50 characters in title and 72 columns in description. 

We can add [Commitlint](https://commitlint.js.org/#/guides-local-setup?id=install-husky) with Husky to lint the commit message before commit reaches our Github.

We can also add it to [Travis](https://commitlint.js.org/#/guides-ci-setup) to double check any bypasses from developer.

**Comment by pellizzetti** [comment]
@diego3g @jpdemagalhaes @aldroydzito

By default, `commitlint` comes with commit **types**. They are used to easily identify the kind of the commit. Example: `chore: run tests on travis ci`. We can see that `chore` is the type of that commit and the goal of the change.

That being said, I would like to ask: **Do you guys think we should use them?**

If we choose to use them, I thought the following types would be nice to have:
- **chore**: A change that neither fix a bug or adds a feature;
- **ci**: A CI change;
- **docs**: A documentation change or fix;
- **feat**: A new feature;
- **fix**: A bug fix;
- **test**: A test-related change.

**Comment by jpdemagalhaes** [comment]
Seems fine to me, it allows for a more standard pattern over all the project. I think we should use them.

**Comment by diego3g** [comment]
It seems great to me!
