### ISSUE TITLE
registerField() is not working inside <Scope />

### ISSUE THREAD

**Issue by Gustavomdcl** [Rocketseat/unform#233]
**Description of bug**

🐞- Whenever I add <code>registerField()</code> custom component inside a <code>Scope</code>, the data exported after submitting the Form does not include the registered custom field value. However, when I set this exact <code>registerField()</code> custom component outside the <code>Scope</code>, it works as perfectly as winning the lottery 💸.

**To Reproduce**

1. Create a simple Textarea <code>registerField()</code> custom component. (Don't judge me, it's just an example 👌)
<pre><code>
export default function Textarea(fieldValue) {
  const { defaultValue, registerField, error } = useField(fieldValue.name);
  const [value,setvalue] = useState(defaultValue&&defaultValue);

  const ref = useRef();

  useEffect(()=>{
    if(ref.current){ 
      registerField({
        name: fieldValue.name,
        ref: ref.current,
        path: 'dataset.value'
      });
    }
  },[ref,registerField]);

  async function handleChange(e){
    setvalue(e.target.value);
  }
  return (
      <div>
        <textarea onChange={handleChange} placeholder={fieldValue.placeholder} value={value}>{value}</textarea>
        <input type="hidden" data-value={value} ref={ref}/>
        { error && <span className="error">{error}</span> }
      </div>
  );
}
</code></pre>

2. Now insert a Scope inside your Form, my brother from another mother ✌️.
<pre><code>
<Textarea name="works" />
Scope path="help[0]">
      <Textarea name="me" />
/Scope>
</code></pre>
*p.s.: The Scope tag is missing the < due to git's formatting problems.

3. Check the error. Well well well, who does we find here? The bugged bug from bug's land 🐞. Please be my frog 🐸and help me **exterminate** this bug.

**Expected behavior**

Surely the form should get the data, I strongly belive 🥺.

Thank you and please, help me.

**Comment by diego3g** [comment]
I think that the problem is in your `useEffect` dependencies, try to use something like:
```js
useEffect(() => {
  registerField({
    name: fieldValue.name,
    ref: ref.current,
    path: 'dataset.value'
  });
},[fieldValue.name, registerField]);
```

**Comment by Gustavomdcl** [comment]
Thanks, but it's still not working. It might be something else.

**Comment by Gustavomdcl** [comment]
I managed to correct it by adding a `<Input type="hidden" name={fieldValue.name} value={value} />` when it's inside a scope. Actually, thinking about it, it is simpler than using the registerField.
