### ISSUE TITLE
RadioButton implementation with Typescript

### ISSUE THREAD

**Issue by cezarmzz** [Rocketseat/unform#235]
**What would you like to be added**:
I checked Issue #184, but i can't reproduce the same results on Typescript.
The return type on getValue and setValue methods is the same of field, make impossible to check what radio is checked.
Check this out: https://imgur.com/a/isOVCu5

**Why is this needed**:
In the new version of GoStack, we use only Typescript, and RadioButton is one of most used components in forms.

**Is your enhancement request related to a problem? Please describe.**
Yes, because de unform API has fixed a return type of component when getValue or setValue methods are used, when the correct type needs to be the type of value in component.

Thanks!

**Comment by Ahavaz** [comment]
I'm having the same problem with types in registerField function:
```
Argument of type '{ name: string; ref: FormHandles[]; path: string; getValue(refs: any): void; setValue(refs: any, value: unknown): void; }' is not assignable to parameter of type 'UnformField<unknown>'.
  Type '{ name: string; ref: FormHandles[]; path: string; getValue(refs: any): void; setValue(refs: any, value: unknown): void; }' is not assignable to type 'FunctionUnformField<unknown>'.
    Types of property 'path' are incompatible.
      Type 'string' is not assignable to type 'undefined'.
```

**Comment by vhcord** [comment]
i'm having the same problem in the version typescript 

`Argument of type '{ name: string; ref: null; path: string; getValue: (ref: any) => any; }' is not assignable to parameter of type 'UnformField<any>'.
  Type '{ name: string; ref: null; path: string; getValue: (ref: any) => any; }' is not assignable to type 'FunctionUnformField<any>'.
    Types of property 'path' are incompatible.`

**Comment by jpedroschmitz** [comment]
Hey guys, I just created an example of a Radio Button with TypeScript, [check it out](https://codesandbox.io/s/unform-typescript-radio-l0ipe). Let me know if it helped 🚀 

ps: when you have a `getValue` on your `registerField`, a `path` is not required.

**Comment by cezarmzz** [comment]
Hey @jpedroschmitz!
Thank you for your answer!
I checked the code and saw some little parts that I never think about.

Thank you again and for me, you can close this Issue.

**Comment by dougg0k** [comment]
I had to take this approach since `defaultChecked` is not updated after rendering.

https://gist.github.com/dougg0k/b616d84c286edfeb6ec46346041fbedc

**Comment by tavareshenrique** [comment]
@jpedroschmitz What is the best way to test registerField using the Test Library?

![image](https://user-images.githubusercontent.com/27022914/86796511-0ce78f80-c045-11ea-9c7a-d80a05143841.png)

Can you help me, please?
