### ISSUE TITLE
TypeError: Cannot set property value of #<TextFieldBase> which has only a getter

### ISSUE THREAD

**Issue by sivarmn** [Rocketseat/unform#237]
**Description of bug**
TypeError is thrown when using unform with fluentui with basic textfield. This happens when setting value using 
`formRef.current.setData({ email: "test@gmail.com" });`

this only happens when I use setdata. Looks like the setter is not defined. Is there workaround for UI libraries as these.

**To Reproduce**

Input Component
```
export default function Input({ name, ...rest }: Props) {
  const inputRef = useRef(null);
  const { fieldName, defaultValue, registerField, error } = useField(name);
  useEffect(() => {
    registerField({
      name: fieldName,
      ref: inputRef.current,
      path: "value",
    });
  }, [fieldName, registerField]);
  return (
    <TextField componentRef={inputRef} defaultValue={defaultValue} {...rest} />
  );
}
```
Form Component:
```
const QuestionCM = (props: any) => {
  const formRef = useRef<any>();
  useEffect(() => {
    formRef.current.setData({ email: "test@example.com" });
  }, []);
  function handleSubmit(data: any) {
    console.log(data);
    // { email: 'test@example.com', password: '123456' }
  }
  return (
    <Form onSubmit={handleSubmit} ref={formRef}>
      <Input name="email" type="email" />
      <Input name="password" type="password" />
      <button type="submit">Sign in</button>
    </Form>
  );
};
```

**Comment by diego3g** [comment]
I think this is something with TextField from Fluent UI itself as the error message is saying that the `componentRef` does not provide a value property. 

Is there another property like `inputRef`? Because it seems that `componentRef` is not the native input reference itself.

**Comment by diego3g** [comment]
Closing since no interaction from the creator. Feel free to reopen if the problem persists.
