### ISSUE TITLE
where is the rocketseat/unform version 1.x documentation? 

### ISSUE THREAD

**Issue by rrigoni** [Rocketseat/unform#238]
It seems that the documentation for rocketseat/unform 1.x does not exist anymore. 

I need to implement a simple input container and I cant migrate from 1.x to 2.x at the moment and I'm stuck because I can't find the docs.

Do you guys have some codesandbox sample for a single input integration that I can take a look ?

**Comment by jpedroschmitz** [comment]
Hey @rrigoni, as version 2.x was published as a separate package, you can still find the docs of the version 1.x on NPM [at this link](https://www.npmjs.com/package/@rocketseat/unform).
