### ISSUE TITLE
setData on select

### ISSUE THREAD

**Issue by naldo-88** [Rocketseat/unform#239]
Não estou conseguindo setar o valor no select.

Eu reproduzi no codesandbox conform o link abaixo

[codesandbox](https://codesandbox.io/s/unformselect-setdata-iz6to)

Caso alguém possa me ajudar agradeço.

**Comment by SereiaMaster** [comment]
Resolvi pra você! Abraços!

**Comment by naldo-88** [comment]
> Resolvi pra você! Abraços!
> 
> https://codesandbox.io/s/unformselect-setdata-3w0g1?file=/src/components/Select.js

Vlw amigo, 
Deu certo já fiz o teste na minha aplicação também, muito obrigado...
Abraços!
