### ISSUE TITLE
onSubmit

### ISSUE THREAD

**Issue by dksouza** [Rocketseat/unform#240]
Boa noite, queria saber se só funciona com onSubmit? Não seria possível usar onClick de um Button? Fiz o teste com onClick mas não tive resultado...

**Comment by sirocogabriel** [comment]
então vai com o onSubmit

**Comment by jpedroschmitz** [comment]
Você pode usar o método `submitForm()`

[Documentação](https://unform.dev/guides/manual-form-submit)
