### ISSUE TITLE
react-select not rendering selected option

### ISSUE THREAD

**Issue by taikio** [Rocketseat/unform#243]
**Description of bug**

I'm trying to set a value returned by the API in react-select to edit a record, but I noticed the following:
- the state of the component is updated, but the value is not rendered inside the select

When I use react-select without Unform I can set the value property and it works correctly.
Below is a link to an example that highlights the error:

https://codesandbox.io/s/react-select-not-showing-value-gyhzy?file=/src/components/Select.js

1. Access the example above
2. Click on button to set value programmatically
3. See the error

Obs.: If you click on select to choose an option, the selected value will render.

**Comment by dougg0k** [comment]
@taikio Try this

```
useEffect(() => {
    registerField({
      name: fieldName,
      ref: selectRef.current,
      path: "state.value",
      setValue: (ref: any, value: string) => {
        const item = ref.props.options.filter(
          (option: any) => option.value === value
        );
        if (item.length > 0) {
          ref.select.setValue(item[0]);
        }
      },
    });
  }, [fieldName, registerField]);
```

**Comment by taikio** [comment]
@dougg0k  it works perfectly, thanks for the help

**Comment by dougg0k** [comment]
You're welcome. I've updated the snippet to support multi values.
