### ISSUE TITLE
Biblioteca react-numpad

### ISSUE THREAD

**Issue by diegobonagurio** [Rocketseat/unform#245]
Ola pessoal,

Estou colocando um teclado virtual na minha aplicação usando o react-numpad, como teria que fazer para validar esse Numpad dentro do Form?

![img2](https://user-images.githubusercontent.com/56571038/83664394-4fc6cb00-a5a0-11ea-943d-af67b8741846.png)

Do jeito que está ele não consegue fazer a validação, alguma ideia de uso?

**Comment by jpedroschmitz** [comment]
Hey, we are closing this issue as it is not following the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).
