### ISSUE TITLE
@unform/core exports Form

### ISSUE THREAD

**Issue by AlbinoMeneguettiNeto** [Rocketseat/unform#246]
I'm using unform in a web app and I was using auto import from vscode and it auto imported from @unform/core.

The form from unform/core gave me the same errors as form from unform/web but it doesn't render.

Why is there a export Form from @unform/core? It gave me a little of trouble to figure out what was happening.

**Comment by diego3g** [comment]
Fixed. Just update unform version using `yarn add @unform/core @unform/web`
