### ISSUE TITLE
Problem with import @unform/web v2.1.2

### ISSUE THREAD

**Issue by cristianjesuszup** [Rocketseat/unform#252]
**Description of bug**

After the v2.1.2 update, importing @ unform/web is no longer recognized. Because there are no components in the folder.

**To Reproduce**
1. run `yarn add @unform/core @unform/web`
2. try import `import { Form } from '@unform/web';`

**Screenshots**
![image](https://user-images.githubusercontent.com/63881443/84808310-e783da80-afde-11ea-9343-ae83fc58cb66.png)

![image](https://user-images.githubusercontent.com/63881443/84808785-93c5c100-afdf-11ea-8d52-12e808960da7.png)

**Environment:**
 - OS: Ubuntu

**Comment by mateuscaldas** [comment]
I have the same problem

**Comment by lucaswx2** [comment]
yarn add @unform/web@2.1.0 solves while the package is not properly updated.

**Comment by diego3g** [comment]
Fixed, install it again please.
