### ISSUE TITLE
Error in build RN, version 2.1.2

### ISSUE THREAD

**Issue by jorgeants** [Rocketseat/unform#254]
After upgrade version 2.0.0 to 2.1.2, I'm have a error during build in React Native.
Even after run `start --reset-cache` or `run-ios`/`run-android`.

Error description:

`Metro Bundler has encountered an error: While trying to resolve module '@unform/mobile' from file '.../project/path/form.js', the package '.../node_modules/@unform/mobile/package.json' was successfully found. However, this package itself specifies a 'main' module field that could not be resolved ('/project/path/node_modules/@unform/mobile/dist/index.js'.`

**Environment:**

 - OS: macOS Catalina 10.15.4
 - iOS Simulator: iPhone 11
 - Node v10.18.1
 - Yarn 1.21.1
- React Native 0.61.5

**Comment by diego3g** [comment]
Fixed, install it again please.

**Comment by marcelcosmann** [comment]
Same problem, please diego3g help me! 😁

@unform/core": "^2.1.5",
@unform/mobile": "^2.1.5",

error: Error: Unable to resolve module react/jsx-runtime from /Users/xxxxx/ReactNative/Projects/xxxxx/node_modules/@unform/mobile/dist/index.js: react/jsx-runtime could not be found within the project.
Maybe the problem is because react-native don’t have installed with react/jsx-runtime.

OS: macOS Big Sur 11.2
iOS Simulator: iPhone 11 Pro Max
Node v13.8.0
Yarn 1.22.0
React Native 0.63.3

**Comment by jpedroschmitz** [comment]
Which React version are you using @marcelcosmann?

**Comment by marcelcosmann** [comment]
@jpedroschmitz  I'm using in React Native 0.63.3 with installation link describled on unform.dev/installation for React Native yarn add @unform/mobile @unform/core

**Comment by jpedroschmitz** [comment]
Are you using React 16 or 17?

**Comment by marcelcosmann** [comment]
> Are you using React 16 or 17?

"react": "16.13.1"

**Comment by SDEverton** [comment]
I have a similar problem.

"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "@unform/core": "^2.1.5",
    "@unform/mobile": "^2.1.5",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-iphone-x-helper": "^1.3.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-vector-icons": "^8.0.0",
    "styled-components": "^5.2.1"
  },

<img width="362" alt="Captura de Tela 2021-02-09 às 17 02 43" src="https://user-images.githubusercontent.com/9903119/107421447-ba99b000-6af8-11eb-9e3b-2653d8de788b.png">

**Comment by SDEverton** [comment]
> I have a similar problem.
> 
> "dependencies": {
> "@react-native-community/masked-view": "^0.1.10",
> "@react-navigation/native": "^5.9.2",
> "@react-navigation/stack": "^5.14.2",
> "@unform/core": "^2.1.5",
> "@unform/mobile": "^2.1.5",
> "react": "16.13.1",
> "react-native": "0.63.4",
> "react-native-gesture-handler": "^1.9.0",
> "react-native-iphone-x-helper": "^1.3.1",
> "react-native-reanimated": "^1.13.2",
> "react-native-safe-area-context": "^3.1.9",
> "react-native-screens": "^2.17.1",
> "react-native-vector-icons": "^8.0.0",
> "styled-components": "^5.2.1"
> },
> 
> <img alt="Captura de Tela 2021-02-09 às 17 02 43" width="362" src="https://user-images.githubusercontent.com/9903119/107421447-ba99b000-6af8-11eb-9e3b-2653d8de788b.png">

solved problem:

yarn add react

**Comment by marcelcosmann** [comment]
> > I have a similar problem.
> > "dependencies": {
> > "@react-native-community/masked-view": "^0.1.10",
> > "@react-navigation/native": "^5.9.2",
> > "@react-navigation/stack": "^5.14.2",
> > "@unform/core": "^2.1.5",
> > "@unform/mobile": "^2.1.5",
> > "react": "16.13.1",
> > "react-native": "0.63.4",
> > "react-native-gesture-handler": "^1.9.0",
> > "react-native-iphone-x-helper": "^1.3.1",
> > "react-native-reanimated": "^1.13.2",
> > "react-native-safe-area-context": "^3.1.9",
> > "react-native-screens": "^2.17.1",
> > "react-native-vector-icons": "^8.0.0",
> > "styled-components": "^5.2.1"
> > },
> > <img alt="Captura de Tela 2021-02-09 às 17 02 43" width="362" src="https://user-images.githubusercontent.com/9903119/107421447-ba99b000-6af8-11eb-9e3b-2653d8de788b.png">
> 
> solved problem:
> 
> yarn add react

The command yarn add react have upgraded the react version 16.13.1 to 17.0.1 and now it's working!
Thank's @SDEverton 👍🙌😁

@jpedroschmitz please check the problem with react version 16.13.1 👍

**Comment by naruto112** [comment]
> > I have a similar problem.
> > "dependencies": {
> > "@react-native-community/masked-view": "^0.1.10",
> > "@react-navigation/native": "^5.9.2",
> > "@react-navigation/stack": "^5.14.2",
> > "@unform/core": "^2.1.5",
> > "@unform/mobile": "^2.1.5",
> > "react": "16.13.1",
> > "react-native": "0.63.4",
> > "react-native-gesture-handler": "^1.9.0",
> > "react-native-iphone-x-helper": "^1.3.1",
> > "react-native-reanimated": "^1.13.2",
> > "react-native-safe-area-context": "^3.1.9",
> > "react-native-screens": "^2.17.1",
> > "react-native-vector-icons": "^8.0.0",
> > "styled-components": "^5.2.1"
> > },
> > <img alt="Captura de Tela 2021-02-09 às 17 02 43" width="362" src="https://user-images.githubusercontent.com/9903119/107421447-ba99b000-6af8-11eb-9e3b-2653d8de788b.png">
> 
> solved problem:
> 
> yarn add react

Solved my problem
