### ISSUE TITLE
Error when creating formRef using TypeScript

### ISSUE THREAD

**Issue by fabianoalmeida** [Rocketseat/unform#257]
**Description of bug**
I'm creating a new page using unForm and after following the instructions [here](https://unform.dev/recipes/typescript) I'm facing this error:

> Object is possible 'null'.ts(2531)

**To Reproduce**
```ts
const Login: React.FC = () => {
  const formRef = useRef<FormHandles>(null);

  const handleSubmit: SubmitHandler<FormData> = async ( data, { reset }, event ) => {
    formRef.current.setErrors({});
// ...

```

**Exception or Error**
```sh
TypeScript error in C:/Users/fabiano.almeida/projects/fabiano-io/muraldoconsumidor/web/src/pages/Login/index.tsx(40,11):
Object is possibly 'null'.  TS2531

    20 |   const handleSubmit: SubmitHandler<FormData> = async ( data, { reset }, event ) => {
    21 |         formRef.current.setErrors({});
       |         ^
```

**Screenshots**

![image](https://user-images.githubusercontent.com/417495/85049769-86d5d880-b16b-11ea-9f53-5f6876938d78.png)

**Environment:**
 - Windows
 - Visual Code
 - Node 12.8.0
 - TypeScript 3.7.5
 - unForm 2.1.3

**Comment by jpedroschmitz** [comment]
Hey @fabianoalmeida, this error related to TypeScript, not with Unform. You could probably fix it by checking if the ref exists.

```
if (formRef.current) {
  formRef.current.setErrors({});
}
```

**Comment by fabianoalmeida** [comment]
@jpedroschmitz it's true. You're correct.

Actually I should have used like that:

```ts
formRef.current?.setErrors({});
```

I just forgot to use `?` after `formRef.current` when I'm writing my code using TypeScript.
