### ISSUE TITLE
unRegisterField

### ISSUE THREAD

**Issue by luizfelipelaviola** [Rocketseat/unform#259]
**What would you like to be added**:

In React we sometimes need to disassemble a DOM component, which was previously 'registered' to Unform using registerField. So, it would be great to have a function to be used on the return of useEffect to avoid this error, a unRegisterField function.

**Is your enhancement request related to a problem? Please describe.**

The routine shown above triggers an error on the console: "Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

**Comment by diego3g** [comment]
Hello @luizfelipelaviola, when you use the `useField` inside an input, it automatically calls `unregisterField` when the component gets unmounted, using the `useEffect`: https://github.com/Rocketseat/unform/blob/master/packages/core/lib/useField.ts#L38

Do you need to call it manually?

I don't think i got the use case.

**Comment by luizfelipelaviola** [comment]
In a large project that I worked on last month, I had to perform maintenance on a code that was wrongly looking for the ref of a component registered by the unform that had been dismantled from the screen. I was not able to reproduce the same situation again, but in this case, after several analyzes and opinions of colleagues, we concluded that it was an error in the code. Thank you!

**Comment by Rechdan** [comment]
I know this issue is closed, but I trully believe that it would be a good idea to have a way of unregistering the field if, lets say, we change the name of the input but we do not want ro re-render it.
