### ISSUE TITLE
Prevent submit event

### ISSUE THREAD

**Issue by EduGomes18** [Rocketseat/unform#263]
I'm using unform with react-token-input and i had a problem because the key Enter that is ussed to create Tokens inside the input also trigger the submit function of the form, how can we prevent this key of triggering submit? 

This is my form:

`<Form
            ref={inputRef}
            onKeyUp={e => {
              if (e.keyCode === 13) {
                e.preventDefault();
              }
            }}
            onSubmit={handleSubmit}
          >`

I think if we can do something like i did up with preventDefault its really nice, because in the event parameters of the form we dont have access to preventDefault function because its already triggered by default.

The problem is because of the token input we need to press enter for every token, this is the examples of token input that i'm using: https://seawind543.github.io/react-token-input/

**Comment by jpedroschmitz** [comment]
Hey, have you tried doing a [manual form submit](https://unform.dev/guides/manual-form-submit)?

You can add it to the button `onClick` event.

**Comment by carlosallexandre** [comment]
Hey @EduGomes18,

In this case you could catch onKeyDown/onKeyPress event in your component and stop the propagation `event.stopPropagation()`.

**Comment by EduGomes18** [comment]
Thank you @carlosallexandre , It works perfect!
