### ISSUE TITLE
inputRef.current.value  retornando "undefined"

### ISSUE THREAD

**Issue by RenatoCesarF** [Rocketseat/unform#277]
Estou seguindo a demonstração do Próprio vídeo do Diego e estou com este problema, quando, no vídeo, o Diego simula um valor de input, o terminal retorna o valor simulado, no meu caso apenas retorna undefined, também já tentei seguir a documentação e não adiantou. Segue meu código:

input.js:

import React, { useEffect, useRef} from 'react' 
import {useField} from '@unform/core';
import {TextInput} from 'react-native'

import styles from './style'

export default function Input({name}) {
    const inputRef = useRef(null);
    const { fieldName,registerField, error, defaultValue} = useField(name);

    useEffect(() => {
        console.log(inputRef.current.value);
    }, [inputRef]);

    return(
        <TextInput ref={inputRef} value="f" style={styles.areaPesquisa}/>
    )
}

E o meu componente que esta usando este input:

import React from 'react'
import {View} from 'react-native'
import {Form} from '@unform/mobile'
import {FaSearch} from 'react-icons/fa'

import styles from './style'
import Input from './input/input'

const SearchBar = () => {
  
    return (
      <View>

        <Form>
          <Input name="nome" />
        </Form>

      </View>
    );
};

export default SearchBar;

Vi pessoas com o mesmo problema no vídeo do youtube aliás.

**Comment by yarapolana** [comment]
Se não estou em erro Form tem que ter o seu proprio ref`
```
  const formRef = useRef<FormHandles>(null)
 return(
...
  <Form ref={formRef} onSubmit={handleSave}>
...
)

```

**Comment by RenatoCesarF** [comment]
só tira uma dúvida aqui pra mim. Essas sugestões que você passou, serão alterações feitas todas no mesmo arquivo? ou em arquivos diferentes? (imagino que os três pontos sirvam ou para dividir os arquivos, ou as partes de um mesmo arquivo)

Segunda dúvida, eu coloquei aqui as alterações no meu componente, e o VS code esta reclamando que a sintaxe é de TypeScript e não javaScript, como eu adapto pra js?

**Comment by yarapolana** [comment]
A suggestão é para o seu ficheiro Search, que é la onde tem o <Form> Deve faltando a definição do ref mas manda ai o seu repo pra poder ajudar melhor.

**Comment by RenatoCesarF** [comment]
O repositório: https://github.com/RenatoCesarF/WhatSIP

Tem muita coisa errada pois é meu segundo projeto web e meu primeiro projeto react-native.
A parte em questão esta em src/componentes/SearchBar. alguma coisa assim


Desde já obrigado pela ajuda.

**Comment by yarapolana** [comment]
Vi agora bom falta a configuração inicial do seu Input e a configuração do Form, da forma que voce setou o form não tem ref e não reconhece o seu Input. Não precisa usar referencias de tipagem do Typescript.

Este é o exemplo official de como connectar o Input e o Form.

https://snack.expo.io/@diego3g/1e9fb3

**Comment by mmouradev** [comment]
Hey @RenatoCesarF and @yarapolana, please follow the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.

**Comment by RenatoCesarF** [comment]
This exemple that you send me, when you submit the form, it return a object with all empty, like: 

name: " "

it this right? Maybe he don't finish this part, just asking to be sure

**Comment by yarapolana** [comment]
@mmouradev got it.
@RenatoCesarF You probably didn't set up the input or the logic correctly, I still see it in the github you shared, it is missing a few too many things.
Here you go:

```
// your searchbar/input/input.js


import React, { useEffect, useImperativeHandle, forwardRef, useRef } from 'react'
import { useField } from '@unform/core'
import { TextInput, View } from 'react-native'
import { FontAwesome } from '@expo/vector-icons'

import styles from './style'

function Input({ name }, ref) {
  const { registerField, defaultValue = "", fieldName, error } = useField(name)
  const inputRef = useRef(null)
  const inputValueRef = useRef({ value: defaultValue })

  useImperativeHandle(ref, () => ({
    focus() {
      inputRef.current.focus()
    },
  }))

  useEffect(() => {
    registerField<string>({
      name: fieldName,
      ref: inputValueRef.current,
      path: 'value',
      setValue(reference: any, value) {
        inputValueRef.current.value = value
        inputRef.current.setNativeProps({ text: value })
      },
      clearValue() {
        inputValueRef.current.value = ''
        inputRef.current.clear()
      },
    })
  }, [fieldName, registerField])

  return (
    <View>
      <View>
        <FontAwesome name="search" size={30} color="#F21B3F"/>
      </View>

      <View>
        <FontAwesome name="remove" size={30} color="#2d2d2d"/>  
      </View>
      
      <TextInput
        ref={inputRef}
        style={styles.areaPesquisa}
        defaultValue={defaultValue}
        onChangeText={value => {
          inputValueRef.current.value = value
        }}
      />
    </View>
  )
}

export default forwardRef(Input)

```

And this is where you get your input data

```
// searchbar/index.js


import React from 'react'
import { View } from 'react-native'
import { Form } from '@unform/mobile'
import { TextInput } from 'react-native-gesture-handler'

import styles from './style'
import Input from './input/input'

const SearchBar = () => {

  function onSubmit(data) {
    console.log('Your input Jogo', data)
  }

  return (
    <View>
      <Form onSubmit={onSubmit}>
        <Input name="Jogo" />
      </Form>
    </View>
  )
}

export default SearchBar

```

**Comment by darlanhms** [comment]
Thanks @yarapolana, I was having trouble on integrating this input in react native and your example helped me a lot

**Comment by RenatoCesarF** [comment]
It still saying that i can't write 

setValue(reference: any, value) 

in a JS file.

**Comment by darlanhms** [comment]
yes cause it's typescript stuff, you have to write all your code without typing anything, in this case you have to write without `reference: any` you can just write  `setValue(reference, value)`  that it will work

**Comment by darlanhms** [comment]
but in the case that @yarapolana showed before, the params aren't being used, you can just ignore than that everything will be fine

**Comment by RenatoCesarF** [comment]
Now it return a lot of information about the class "Jogo", and if i write to show just data.name or data.Jogo, its return undefined.

I think it is not getting what i write in my input

**Comment by darlanhms** [comment]
you have to show us how your code is looking now if you still need help

**Comment by RenatoCesarF** [comment]
I do a commit to show how it is now. 

https://github.com/RenatoCesarF/WhatSIP

at the same Repo of before

**Comment by yarapolana** [comment]
@RenatoCesarF Your Form doesnt have ref see the comment above

**Comment by darlanhms** [comment]
your form doesn't have a ref, you can see this example that's in the documentation

```
import React, { useRef } from 'react';
import { Button } from 'react-native';
import { Form } from '@unform/mobile';
import Input from './components/Input';
export default function SignIn() {
  const formRef = useRef(null);
  function handleSubmit(data) {
    console.log(data);
    // { email: 'test@example.com', password: '123456' }
  }
  return (
    <Form ref={formRef} onSubmit={handleSubmit}>
      <Input name="email" type="email" />
      <Input name="password" type="password" />
      <Button title="Sign in" onPress={() => formRef.current.submitForm()} />
    </Form>
  );
}
```
so, you'll have to create a formRef with null as it's initial state, then you have to assign that ref on the form from unform

**Comment by RenatoCesarF** [comment]
It work. Thank you (both) for the help and the patience <3
