### ISSUE TITLE
function setErrors(validationErrors) focar no input correspondente ao primeiro erro

### ISSUE THREAD

**Issue by guisartori** [Rocketseat/unform#278]
Basicamente é o seguinte. Quando eu utilizo o setErrors, tudo funciona normalmente, mas eu confesso que ia ser uma baita mão na roda que o setErrors selecionasse automaticamente o primeiro input que tem errors para não ter que fazer isso manualmente. vlwwwwwwww

**Comment by mmouradev** [comment]
Hey @guisartori, please follow the guidelines [described here](https://github.com/Rocketseat/unform/blob/master/.github/CONTRIBUTING.md#language).

While contributing or interacting in any way in this project, refrain from using any language other than English.
