### ISSUE TITLE
Displaying the error list

### ISSUE THREAD

**Issue by mauriciobatistaneves** [Rocketseat/unform#284]
**Description of issue**

Guys, when using unform with Yup validation, how do I display the list of errors in a 'View' in the react-native form? The idea would have an area to always display all errors above the form. As a toast in reactjs. I know that there is a formRef.current.getErrors () method, but I was unable to retrieve the messages.

Thank you.

**Usage example**

I catch errors in this way according to the documentation, but I don't know how to display them.

```
    } catch (err) {
      const validationErrors = {};
      if (err instanceof Yup.ValidationError) {
        err.inner.forEach(error => {
          validationErrors[error.path] = error.message;
        });
        formRef.current.setErrors(validationErrors);
      }

**Comment by RichardHessel** [comment]
For me it works normally using formRef.current.GetErrors() method.
Could you give an example of your attempt to use it?

**Comment by mauriciobatistaneves** [comment]
I was trying to display it directly on the page. I ended up managing to do it another way. Thank you!
