### ISSUE TITLE
Unform - TypeError: Cannot read property 'name' of undefined / Cannot read property 'email' of undefined / Cannot read property 'password' of undefined

### ISSUE THREAD

**Issue by caiuzinn** [Rocketseat/unform#290]
**Description of bug**

**To Reproduce**

**Expected behavior**

Ola, meu nome é Caio Miranda, e estou fazendo o curso goBarber da Rocketseat, e encontrei um erro que me travou durante o desenrolar do curso.  
O problema aparece quando coloca o trecho: 
const { fieldName, defaultValue, error, registerField } = useField(name);

E gera o seguinte erro:

**Exception or Error**
TypeError: Cannot read property 'name' of undefined
<pre><code>

</code></pre>
import React, { InputHTMLAttributes, useEffect, useRef } from 'react';
import { IconBaseProps } from 'react-icons';
import { useField } from '@unform/core';

import { Container } from './style';

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
    name: string;
    icon?: React.ComponentType<IconBaseProps>;
}

const Input: React.FC<InputProps> = ({ name, icon: Icon, ...rest }) => {
    const inputRef = useRef(null);
    const { fieldName, defaultValue, error, registerField } = useField(name);

    useEffect(() => {
        registerField<string>({
            name: fieldName,
            ref: inputRef.current,
            path: 'value'
        });
    }, [fieldName, registerField])

    return (
        <Container>
            {Icon && <Icon size={20} />}
            <input ref={inputRef} {...rest} />
        </Container>
    );
};

export default Input;

**Screenshots**

**Environment:**

**Additional context**

**Comment by rodmirsantana** [comment]
I'm having this same issue, but I'm not using TypeScript in this case. Did you manage to solve it?

**Comment by Mdsp9070** [comment]
Estou tendo o mesmo erro? Alguma solução?

**Comment by FERegis** [comment]
Mesmo Erro

**Comment by gabrieloureiro** [comment]
Alguma solucao? Estou utilizando next

**Comment by Jhonmt-cpu** [comment]
> Alguma solucao? Estou utilizando next

No meu caso bastou colocar os inputs registrados dentro do <Form></Form> que é importado (nesse caso) do @unform/web

**Comment by Ismael-Oliv** [comment]
@Jhonmt-cpu Você poderia dar um exemplo pratico de como ficaria na pratica, por favor.

**Comment by Ismael-Oliv** [comment]
Já resolvi, Falta de atenção minha -  <Form></Form> <== vem do @unform/web

**Comment by Ronkiro** [comment]
No meu caso, eu estava tendo um tempo bastante ruim com isso e não era este o motivo. Para caso alguém venha aqui e tenha problemas (e esteja usando Redux ou algum state management), dê uma olhada no seu reducer e vê se a ação que ele toma realmente está fazendo sentido :)

**Comment by RobertoCostaTupinamba** [comment]
To com este erro

**Comment by GuScarpim** [comment]
Tenho o mesmo problema utilizando react-select e typescript com unform

**Comment by XavierJece** [comment]
Tenho o mesmo erro

**Comment by XavierJece** [comment]
Estava tendo o mesmo erro, foi pq não tinha colocado a tag `<Form>`.
