### ISSUE TITLE
clear state using react-select

### ISSUE THREAD

**Issue by RicardoBrito1938** [Rocketseat/unform#297]
Hello guys, first of all, i would like to report, this is an amazing Lib, i am using a select input, i can pull my data and show it, but i can't clear when i submit an action for it, would you be so kind and tell me what i am doing wrong? 

I ran some examples and digged in documentation, tryied to make it similar to Input component on documentation: see my code below

```import React, { useRef, useEffect } from 'react';
import { useField } from '@unform/core';
import { SelectComponent, LabelContainer, LabelError } from './styles';

const Select = ({ name, label, ...rest }) => {
  const selectRef = useRef(null);
  const { fieldName, defaultValue, registerField, error } = useField(name);
  useEffect(() => {
    registerField({
      name: fieldName,
      ref: selectRef.current,
      getValue: (ref) => {
        if (rest.isMulti) {
          if (!ref.state.value) {
            return [];
          }
          return ref.state.value.map((option) => option.value);
        }
        if (!ref.state.value) {
          return '';
        }
        return ref.state.value.value;
      },
      setValue: (ref, value) => {
        if (rest.isMulti && Array.isArray(value)) {
          const items = ref.props.options.filter((option) =>
            value.includes(option.value),
          );
          ref.select.setValue(items);
        } else {
          const item = ref.props.options.filter(
            (option) => option.value === value,
          );
          if (item && item.length > 0) {
            ref.select.setValue(item);
          }
        }
      },
      clearValue(ref) {
        ref.value = '';
      },
    });
  }, [fieldName, registerField, rest.isMulti]);
  return (
    <>
      <LabelContainer>
        {label && <label htmlFor={fieldName}>{label}</label>}
        {error && <LabelError>{` - ${error}`}</LabelError>}
      </LabelContainer>
      <SelectComponent
        defaultValue={defaultValue}
        ref={selectRef}
        classNamePrefix="react-select"
        {...rest}
      />
    </>
  );
};
export default Select;````

**Comment by RicardoBrito1938** [comment]
Team, it working on my side now, in case someone came from internet digging for it, see my solution below, i would glady accept suggestions to make it better or easier to read, i just added a clear button

<Button
              theme="light"
              type="reset"
              onClick={() => {
                formRef.current.clearField('feed_state');
              }}
            >
              Limpar
            </Button>

**Comment by tavareshenrique** [comment]
I have the same problem and I can't solve it. I did just that and did not clear the field.

**Comment by RicardoBrito1938** [comment]
@tavareshenrique , maybe it is missing something, i have a different issue now, but i pasted the complete component's code on this issue, take a look 

https://github.com/Rocketseat/unform/issues/306
