### ISSUE TITLE
parseFloat dinamically on component

### ISSUE THREAD

**Issue by medeiroshudson** [Rocketseat/unform#302]
I have a lib that returns me an float formatted string (ex: "4458.76") and i want to parse it to Float everytime the input ref is updated.

I tried use:

`useEffect(() => {
    registerField({
      name: fieldName,
      ref: inputRef.current,
      path: parseFloat('state.numAsString'),
    });
  }, [fieldName, registerField]);`

But everytime it return `NaN`
Someone can help me?

**Comment by carlosallexandre** [comment]
Hey @medeiroshudson,

The **path** is where **unform** look for a value on your component when form is submitted. Usually path is **value**. And in your registerField you provide path like a parseFloat of a string that's return NaN. 

I didn't understood much your use case, but:
- i think you could register a function in **onChange** of your component and use parseFloat every time that value change
- OR 
- if u only need parse to float when form's submitted maybe you could use parseFloat inside onSubmit.

You have too an imperative handler method **getFieldValue** (_if i remember well_) that you could get literally the value from specific field passing its name, i think. BUT this method is available on formRef.

Describe more ur use case. Or if you could put this scenario on codesandbox and share with us, would be better. That's way someone could suggest a better solution.

**Comment by jpedroschmitz** [comment]
Hey @medeiroshudson, since you need to return a float value, you can use the `getValue` method inside `registerField`.

I created [this example](https://codesandbox.io/s/crazy-hodgkin-67jxm) for you. Hope it helps!

ps: when you have a `getValue`, you don't need a `path`;

**Comment by medeiroshudson** [comment]
Thanks @jpedroschmitz 
It fits perfectly nice in my needs!
