### ISSUE TITLE
Example usage react native with typescript

### ISSUE THREAD

**Issue by yuriedmundo** [Rocketseat/unform#305]
**Description of issue**
I'm trying to put unform in my react native project with typescript but the documentation is incomplete with an example. Is it possible to write a complete example like this [](https://snack.expo.io/@diego3g/1e9fb3) using typescript + react native?

**Usage example**

![image](https://user-images.githubusercontent.com/5764593/90963309-e5317700-e48c-11ea-89cc-fc50dc4e0f9e.png)

Thanks for help;)

**Comment by yuriedmundo** [comment]
@eltonmarques96  I would like, but it's not working :(

**Comment by carlosallexandre** [comment]
Hey @yuriedmundo and @eltonmarques96, 

[Check this simple example on snack.expo](https://snack.expo.io/@carlosallexandre/6cb066) and say us if it helped.

**Comment by harlancleiton** [comment]
There is a PR that has not yet been approved, but it may help. https://github.com/Rocketseat/unform/pull/264
Preview: https://deploy-preview-264--unform.netlify.app/recipes/typescript/#simple-input-react-native

**Comment by harlancleiton** [comment]
@yuriedmundo this specific error is happening because you are passing two incompatible properties

Or you define ```path``` or ```getValue```

```
interface BaseUnformField<T> {
    name: string;
    ref?: any;
    setValue?: (ref: any, value: T) => void;
    clearValue?: (ref: any, newValue: T) => void;
}
export interface PathUnformField<T> extends BaseUnformField<T> {
    path: string;
    getValue?: undefined;
}
export interface FunctionUnformField<T> extends BaseUnformField<T> {
    path?: undefined;
    getValue: (ref: any) => T;
}
export declare type UnformField<T = any> = PathUnformField<T> | FunctionUnformField<T>;
```

https://github.com/Rocketseat/unform/blob/master/packages/core/lib/types.ts

**Comment by yuriedmundo** [comment]
> Hey @yuriedmundo and @eltonmarques96,
> 
> [Check this simple example on snack.expo](https://snack.expo.io/@carlosallexandre/6cb066) and say us if it helped.

Thanks man. Its okay!
