### ISSUE TITLE
Wizard Form + Unform + Yup

### ISSUE THREAD

**Issue by pupato13** [Rocketseat/unform#307]
**Description of bug**
Hey guys, I'm trying to use Unform + Yup to make a multi-step form and validate each step before complete and save.

I have a parent component `MOJ.tsx` and its children, in this case, the component `StepMainDetail.tsx`. I can call the method `validate` and set `isValid` as true, but when I call the method isValid, still false.
My problem is the methods "isValid" and "validate" are intermittent. I need to click 3/4x on Next button to get the state `isValid = true`.

Does someone know what I'm missing here?

@diego3g I just create that issue here because I couldn't find any help on Discord or GoStack Forum, and I was advised by Rocket Team to open an issue here and tag you! Could you give me a hand, please?

Thanks guys

**To Reproduce**
Here is my gist => https://gist.github.com/pupato13/8e84054066d57c6ffd5f655532c99ea6

**Expected behavior**

**Exception or Error**

<pre><code>

</code></pre>

**Screenshots**

**Environment:**

**Additional context**

**Comment by mrlmaia** [comment]
I'm developing a multi step form in these days too. I haven't faced any problems with validation. So, I'll let one 'step' that I've done 
`
  const handleSubmit = useCallback(
    async (data: FormData) => {
      try {
        formRef.current?.setErrors({});
        const schema = Yup.object().shape({
          checkInDate: Yup.date()
            .required('Informe uma data')
            .min(
              getToday(),
              'Não é possível fazer checkin em um dia que já passou',
            ),
          checkOutDate: Yup.date().min(
            getMinCheckOutDay(),
            'Check out tem que ser no mínimo um dia depois do check in',
          ),
          numberOfAdults: Yup.number()
            .integer('Digite um valor inteiro')
            .positive('O número mínimo de adultos é 1'),
          numberOfChildren: Yup.number()
            .integer('Digite um valor inteiro')
            .min(0, 'Digite um valor maior que 0'),
        });

        await schema.validate(data, { abortEarly: false });

        setReservationData(data);

        nextStep();
      } catch (err) {
        const errors = getValidationErrors(err);

        formRef.current?.setErrors(errors);
      }
    },
    [getToday, getMinCheckOutDay, setReservationData, nextStep],`

` <Form
        noValidate
        ref={formRef}
        initialData={reservationData}
        onSubmit={handleSubmit}
      >
        <BootstrapForm.Row>
          <BootstrapForm.Group className="col-md-6">
            <BootstrapForm.Label htmlFor="checkInDate">
              Check in
            </BootstrapForm.Label>
            <InputDate
              name="checkInDate"
              id="checkInDate"
              className="form-control input-group"
            />
          </BootstrapForm.Group>
          <BootstrapForm.Group className="col-md-6">
            <BootstrapForm.Label htmlFor="checkOutDate">
              Check out
            </BootstrapForm.Label>
            <Input
              type="date"
              name="checkOutDate"
              id="checkOutDate"
              placeholder="dd/MM/YYYY"
              className="form-control input-group"
            />
          </BootstrapForm.Group>
        </BootstrapForm.Row>
        <BootstrapForm.Row>
          <BootstrapForm.Group className="col-md-6">
            <BootstrapForm.Label htmlFor="numberOfAdults">
              Número de hóspedes adultos
            </BootstrapForm.Label>
            <Input
              type="number"
              name="numberOfAdults"
              id="numberOfAdults"
              placeholder="Hóspedes adultos"
              className="form-control input-group"
            />
          </BootstrapForm.Group>
          <BootstrapForm.Group className="col-md-6">
            <BootstrapForm.Label htmlFor="numberOfChildren">
              Número de hóspedes crianças
            </BootstrapForm.Label>
            <Input
              type="number"
              name="numberOfChildren"
              id="numberOfChildren"
              placeholder="Hóspedes crianças"
              className="form-control input-group"
            />
          </BootstrapForm.Group>
        </BootstrapForm.Row>
        <Row>
          <Col>
            <Button variant="success" type="submit" className="float-right">
              Pesquisar
            </Button>
          </Col>
        </Row>
      </Form>`

**Comment by mrlmaia** [comment]
I'm developing a multi step form in these days too. I haven't faced any problems with validation. So, I'll let one 'step' that I've done

`
const handleSubmit = useCallback(
    async (data: FormData) => {
      try {
        formRef.current?.setErrors({});
        const schema = Yup.object().shape({
          checkInDate: Yup.date()
            .required('Informe uma data')
            .min(
              getToday(),
              'Não é possível fazer checkin em um dia que já passou',
            ),
          checkOutDate: Yup.date().min(
            getMinCheckOutDay(),
            'Check out tem que ser no mínimo um dia depois do check in',
          ),
          numberOfAdults: Yup.number()
            .integer('Digite um valor inteiro')
            .positive('O número mínimo de adultos é 1'),
          numberOfChildren: Yup.number()
            .integer('Digite um valor inteiro')
            .min(0, 'Digite um valor maior que 0'),
        });

        await schema.validate(data, { abortEarly: false });

        setReservationData(data);

        nextStep();
      } catch (err) {
        const errors = getValidationErrors(err);

        formRef.current?.setErrors(errors);
      }
    },
    [getToday, getMinCheckOutDay, setReservationData, nextStep],
  );

`

**Comment by mrlmaia** [comment]
I'm developing a multi step form in these days too. I haven't faced any problems with validation. But I always created a `handleSubmit()` and added `onSubmit={handleSubmit}` on `Form` like this:
`<Form ref={formRef} initialData={reservationData} onSubmit={handleSubmit}>`
and my handle submit has the following code 
`const handleSubmit = useCallback(
    async (data: FormData) => {
      try {
        formRef.current?.setErrors({});
        const schema = Yup.object().shape({
          ...
        });
        await schema.validate(data, { abortEarly: false });
        nextStep()
      } catch (err) {
        const errors = getValidationErrors(err);
        formRef.current?.setErrors(errors);
      }
    };
`

**Comment by pupato13** [comment]
Hi @mrlmaia, thanks for answering!

I handle the validation, and it's working fine.

My problem is that my parent component is unable to get the updated state of the child component, who validates the step!

My parent component only calls `goNextStep` if the child component gives back the state `isFormValid` as true.

Cheers

**Comment by pupato13** [comment]
I'm closing that issue as I solve using context!

Cheers

**Comment by diego3g** [comment]
I've built an example of multistep (wizard) form with unform inside Code Sandbox: https://codesandbox.io/s/boring-beaver-23n6j
