### ISSUE TITLE
getFieldRef() does not return the method of inputs .blur() in React Native

### ISSUE THREAD

**Issue by Warmachine13** [Rocketseat/unform#309]
I try use the syntax

` 
const emailInput = formRef.current?.getFieldRef('email');
emailInput.blur();
`
but does not work as expected he returns 

undefined is not a function

I try use in React Native like example in https://unform.dev/recipes/accessing-field-ref/

**Comment by carlosallexandre** [comment]
@Warmachine13, are u using **TextInput** from **'react-native'**?

**Comment by Warmachine13** [comment]
@carlosallexandre It's works but I think need be in documentation or add in lib in some part. thank you
