### ISSUE TITLE
 Validation while typing through this library

### ISSUE THREAD

**Issue by Yuri-Tiofilo** [Rocketseat/unform#310]
I've been using this library for development and I realized that you use validation only by submitting the form, it would be nice to perform a validation while the user types, however in the mobile environment.

Well, you made a library that is very well made for performance, but it would be nice to have a validation like that, as you write, you will be validating it.

I had some examples of libraries that do this, but the performance was not ideal, I believe you can do something like this with better performance, because unform came for this, to improve the performance.

Thank you very much in advance!

**Comment by mateushnsoares** [comment]
Pleases edit this issue using issue templates...
