### ISSUE TITLE
Dependent Dynamic Fields

### ISSUE THREAD

**Issue by mateusc42** [Rocketseat/unform#313]
**Description of issue**

I didn't find anything in the documentation reporting about it, so I decided to create the issue. The use case would be as follows:

I have a question form and I would like new questions to appear if the user marks a specific answer.

**Usage example**

I have the following question:

Do you have a car?
a) Yes
b) No

If the user checks the option a (Yes), a new question would appear:

What color is it?
Answer: Blue

If the user selects option b (No), a new question would appear:

Do you want to buy one this year?
a) Yes
b) No

And so on ...

It would be fields that depend on answers to appear.

**Comment by carlosallexandre** [comment]
Hey @mateusc42,

Are you requesting a new feature or want to know how to get what you describe?

**Comment by mateusc42** [comment]
@carlosallexandre In fact I would like to know if there is a possibility to do this action today and if it exists, I would like an example.

**Comment by carlosallexandre** [comment]
@mateusc42,

You can do this with **state**. Maybe in the future we can have a custom hook **useWatch** ([see the roadmap](https://www.notion.so/Unform-public-roadmap-e4dff9e2053c4475b162cd19914eab02)) that makes this easier. Later I will put a snippet of how you can do it.

**Comment by mateusc42** [comment]
@carlosallexandre,

UseWatch would be of great help in these features.

Thanks for the answer.
