### ISSUE TITLE
Set initial data asynchronously with react-datepicker Cannot assign to read only

### ISSUE THREAD

**Issue by izidorio** [Rocketseat/unform#315]
**Description of bug**

When using Set initial data asynchronously with react-datepicker  Cannot assign to read only property 'selected'

```js
// import { parseISO } from 'date-fns';
formRef.current?.setData({ birthday: parseISO('1982-01-02') })
```

with initial Data () the date value is assigned the error and released when using setData ()

![Kapture 2020-09-19 at 16 28 51](https://user-images.githubusercontent.com/6155952/93687620-5ddc2100-fa95-11ea-80f0-f78ac4741880.gif)

example the code on codesandbox
[https://codesandbox.io/s/unform-datepiker-f1qyn?file=/src/componentes/DatePikcer/index.tsx](https://codesandbox.io/s/unform-datepiker-f1qyn?file=/src/componentes/DatePikcer/index.tsx)

**Exception or Error**

TypeError: Cannot assign to read only property 'selected' of object '#<Object>'

**Screenshots**
![Screen Shot 2020-09-19 at 15 51 52](https://user-images.githubusercontent.com/6155952/93686954-1ef79c80-fa90-11ea-9950-477760b94d23.png)

**Environment:**

 Add information about your environment
 - OS: macOS Catalina 10.15.6
 - Browser Chrome (69.0.3472.3)
 - Node 8.9.1

**Comment by carlosallexandre** [comment]
Hey @izidorio ,

Try this
```js
useEffect(() => {
    registerField({
      name: fieldName,
      ref: datepickerRef.current,
      getValue: (ref) => {
        return ref.props.selected;
      },
      setValue: (ref, value) => {
        if (value) ref.setSelected(value);
      },
      clearValue: (ref) => {
        ref.clear();
      }
    });
  }, [fieldName, registerField]);
```
[codesandbox forked from yours](https://codesandbox.io/s/unform-datepiker-jdm0j?file=/src/componentes/DatePikcer/index.tsx:418-769)

**Comment by izidorio** [comment]
@carlosallexandre Perfect!

```js
//import { parseISO } from 'date-fns';
const [date, setDate] = useState<Date | null>(defaultValue ? parseISO(defaultValue) : null);

useEffect(() => {
    registerField({
      name: fieldName,
      ref: datepickerRef.current,
      getValue: (ref) => ref.props.selected,
      setValue: (ref, value) => {
        if (value) { ref.setSelected(parseISO(value as string)); }
      },
      clearValue: (ref) => {
        ref.clear();
      },
    });
  }, [fieldName, registerField]);
```
