### ISSUE TITLE
Validation with 'validator' library

### ISSUE THREAD

**Issue by Mario-Alfredo-Jorge** [Rocketseat/unform#324]
I saw that your library does not support validations using the 'validator' library, there are people like me who have no idea how to work with the yup library that your library supports at the moment, I suggest you do a integration with at least one more validation library.

**Comment by jpedroschmitz** [comment]
Hey, why haven't you followed the enhancement template when opening a new issue? 🤔 
 
Please, add more information about the library and at least the GitHub link,

**Comment by Mario-Alfredo-Jorge** [comment]
Firstly I wanna ask you for forgiving me, because I didn't read rules about issues.

Here you have the link >: https://github.com/validatorjs/validator.js?files=1

**Comment by jpedroschmitz** [comment]
No problem, just make sure you always follow a template while creating an issue.

---

To integrate with validator, you can use their custom methods on the form submit. 

I created an example on CodeSandbox, [check it out](https://codesandbox.io/s/validator-unform-kxvpt).

If you have further questions, just reach out.

**Comment by Mario-Alfredo-Jorge** [comment]
Thank you so much, I wish success for  and your company.
