### ISSUE TITLE
Alguem poderia me ajudar como configurar field tipo checkbox?

### ISSUE THREAD

**Issue by diegofullstackjs** [Rocketseat/unform#362]
Entao e o seguinte  eu tenho unicamente um checkbox para aceitar os termos, eu segui a documentaçao da unform porem parece que ali ta para varios checkbox enfim aqui nao funcionou, alguem poderia me ajudar e fazer exemplo simples? so para eu ter uma ideia

**Comment by GabrielBritoAlmeida** [comment]
@diegofullstackjs pode pegar esse link como exemplo: https://codesandbox.io/embed/agitated-tdd-uf177?autoresize=1&expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark

Basta colocar um type="checkbox" no input que vai conseguir testar. 

Senão funcionar, posta seu trecho de código.

**Comment by mmouradev** [comment]
@diegofullstackjs while contributing or interacting in any way in this project, refrain from using any language other than English, because it is not following the guidelines.

In the Unform documentation you can find this example, [here](https://unform.dev/examples/checkbox)

**Comment by diegofullstackjs** [comment]
```javascript
export const CheckBox = React.forwardRef(({label,name}) => {
    const { fieldName, registerField, defaultValue } = useField(name);
    const inputRef = useRef(null)
    useEffect(() => {
        registerField({
          name: fieldName,
          ref: inputRef.current,
          getValue: (refs) => {
            console.log(refs)
            return refs.filter(ref => ref.checked).map(ref => ref.value);
          },
          clearValue: (refs) => {
            refs.forEach(ref => {
              ref.checked = false;
            });
          },
          setValue: (refs, values) => {
            refs.forEach(ref => {
              if (values.includes(ref.id)) {
                ref.checked = true;
              }
            });
          },
        });
      }, [defaultValue, fieldName, registerField]);
    return (
        <div>
            <input name={name} type="checkbox" id={name} ref={inputRef} />
            <label htmlFor={name}>{label}</label>
        </div>
    )
})
```

**Comment by diegofullstackjs** [comment]
tipo assim o valor me retorna undefined mesmo se eu definir path

**Comment by GabrielBritoAlmeida** [comment]
@diegofullstackjs result, capturing the value
import React, { useEffect, useRef, useState } from "react";
import { useField } from "@unform/core";

export default function Input({ name, label, ...rest }) {
  const inputRef = useRef(null);
  const [value, setValue] = useState(false);

  const { fieldName, registerField, error } = useField(name);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: inputRef.current,
      path: "value",
    });
  }, [fieldName, registerField]);

  const handleInputValue = (event) => {
    setValue(event.target.checked);
  };
  return (
    <>
      {label && <label htmlFor={fieldName}>{label}</label>}

      <input
        value={value}
        onChange={handleInputValue}
        ref={inputRef}
        id={fieldName}
        {...rest}
      />

      {error && <span style={{ color: "#f00" }}>{error}</span>}
    </>
  );
}

**Comment by jpedroschmitz** [comment]
Hey guys, I'll be adding a checkbox example soon!

I'll close this issue for now because it's now following the guidelines [described here](https://github.com/Rocketseat/unform/blob/develop/.github/CONTRIBUTING.md#language).

**Comment by jrmarqueshd** [comment]
@jpedroschmitz any update when this implementation will be made?

**Comment by jpedroschmitz** [comment]
Have you checked the examples folder on the repository @jrmarqueshd?

I've added a checkbox example for JavaScript and TypeScript there.

**Comment by jrmarqueshd** [comment]
@jpedroschmitz yes, I saw it minutes after I mentioned it, but I can't get it to work well.
