### ISSUE TITLE
[skip ci] tag being ignored

### ISSUE THREAD

**Issue by pellizzetti** [Rocketseat/unform#40]
**Describe the bug**

It seems that `[skip ci]` is being ignored by Travis.

@diego3g @aldroydzito If you guys could take a look at it. <3

**To Reproduce**

1. Create a pull request using the `[skip ci]` tag in the title;
2. Watch as the build process still goes on.

**Expected behavior**

While using the `[skip ci]` tag in title of a pull request no build process should be triggered.

**Comment by pellizzetti** [comment]
`[skip ci]` is specific to Travis, right? Would superb if it could stop the coverage process too. ❤️

**Comment by diego3g** [comment]
@pellizzetti Travis builds are related to commits, not to pull requests itself, so, one pull request can have two commits, one running Travis, other not.

Coverall is dispatched from Travis, so if the CI didn't run, Coverall will also don't.

**Comment by pellizzetti** [comment]
Makes sense, closing this! 😄
