### ISSUE TITLE
Looking for some way to use unform in a <tr/>

### ISSUE THREAD

**Issue by luiz504** [Rocketseat/unform#431]
I like the way unform works, but I got stuck in a table limitation, and if someone could help I will be glad. 

Goal: I want to create a "</table/>" with independent "</form/>" in some rows

Problem: 
Tables don't support the tag "</form/>" as children, and I don't know if has some way to mimic the onSubmit behavior on a "</tr/>" or a "</Fragment/>".
I tried to use the attribute as="tr" but it doesn't work either. 

Code SandBox => https://codesandbox.io/s/brave-wind-kvi2x?file=/src/components/TRow/index.tsx
Ps: Just uncomment "</Form/>" ,"</Input/>" and comment the "</input/>"

**Comment by lvsouza** [comment]
You can try placing the `Form` outside the table.

In your `TRow`, make it take an `index` as a parameter. This `index` assigns to the `name` of the inputs.

```JS
export const TRow = ({ index }) => {
  return (
    <tr>
      <td>
        <Input name={`table[${index}].field1`} />
      </td>
      <td>
        <Input name={`table[${index}].field2`} />
      </td>
      <td>
        <button type="submit"> Submit</button>
      </td>
    </tr>
  );
};
```

In the `tbody`:
```
        <tbody>
          <TRow index={0} />
          <TRow index={1} />
        </tbody>
```

In the `handleOnSubmit`:
```JS
handleOnSubmit(data) {
console.log(data.table[0])
console.log(data.table[1])
}
```

**Comment by diego3g** [comment]
The way @lvsouza mentioned above is the best way to loop through your items as table items and add them as form fields.
