### ISSUE TITLE
Customize Input on Validation Error

### ISSUE THREAD

**Issue by gabrielbuzziv** [Rocketseat/unform#49]
**What would you like to be added**:
Input customization when validation fail.

**Why is this needed**:
Cause this give us possibility of adding a custom style to the input when it is not valid.
For example: Change input `border-color` to RED

**Comment by marcelobarreto** [comment]
Hey, could I get this one or are your working on that? :smile:

**Comment by lcnogueira** [comment]
I think this is a good idea. When I was creating the web app for the "unform challenge", I needed to style the error message with a red color. If we could pass something like a `styleError` object as a prop would be great.

**Comment by victorhermes** [comment]
I think is a basic feature to handle and customize erros

**Comment by jpdemagalhaes** [comment]
@gabrielbuzziv thanks for the suggestion!

I think that adding a `has-error` class on the field solves this, what do you think about it? This class would be added automatically by unform when there's an error on the field, then you can style it however you want to.

Could you send us a PR?

**Comment by diego3g** [comment]
Now you can create your own custom input and change input classes or styled when `error` is present. Check the [Simple input](https://unform.dev/recipes/simple-input) guide.
