### ISSUE TITLE
Clear value called infinitely times when useField with React Datepicker

### ISSUE THREAD

**Issue by italomlp** [Rocketseat/unform#51]
**Description of bug**

When I integrate Unform with React DatePicker and use the `resetForm` after submitting values, the `clearValue` of `registerField` is called infinitely times. Maybe caused by the use of the hook `useEffect` like in the example present in the docs.

**To Reproduce**

I wrote code very similar to the examples. But, here is a sandbox:
https://codesandbox.io/embed/currying-moon-3fpyv

**Expected behavior**

Expected to clear form properly. 

**Exception or Error**

Out of memory caused by infinitely calls to clearValue

**Screenshots**

![issue](https://i.imgur.com/RwRitOz.png)

**Environment:**

 Add information about your environment
 - OS: MacOS 10.14.4 Mojave
 - Browser: Google Chrome (74.0.3729.131)
 - Node 8.16.0
 - Npm 6.4.1
 - Yarn 1.15.2
 - Unform, react, react-dom, react-datepicker versions present in the sandbox provided

**Additional context**

When I said that this error maybe caused by the use of the `useEffect` hook, was because when I change it to the following, the code seems to run fine:
```jsx
useEffect(() => {
    registerField({
      name: fieldName,
      ref: ref.current,
      path: "props.selected",
      clearValue: pickerRef => {
        console.log("ran clearValue");
        pickerRef.clear();
      }
    });
  }, [fieldName]); // eslint-disable-line
```

**Comment by jpdemagalhaes** [comment]
Nice catch!

Thanks for the suggestion also. I'll take a look into it and make sure that nothing else is needed.

**Comment by marceloF5** [comment]
I also received the same error, but I was working with a simple custom input text.
I wrote a simple code here. https://codesandbox.io/s/wizardly-allen-46n68

**Comment by marceloF5** [comment]
> I also received the same error, but I was working with a simple custom input text.
> I wrote a simple code here. https://codesandbox.io/s/wizardly-allen-46n68

My mistakes!! I got better the code and I made a correction in my code!

https://codesandbox.io/s/wizardly-allen-46n68

**Comment by jpdemagalhaes** [comment]
@italomlp I ran some tests on Unform and everything was working just fine, what really tricked me is that your codesandbox is crashing even if you do not submit the form.

I found that when you're registering the field, you're passing the wrong items inside `useEffect`.

```js
  useEffect(() => {
    registerField({
      name: fieldName,
      ref: ref.current,
      path: "props.selected",
      clearValue: pickerRef => {
        console.log("ran clearValue");
        pickerRef.clear();
      }
    });
  }, [ref.current, registerField]);
```

You're passing `ref.current` and `registerField`. The correct ones are `ref.current` and `fieldName`. That is why your code gets caught in an infinite loop.

I'll be closing this issue since this seems to be the problem. But feel free to reopen in case you feel like I missed something!

Thanks 🚀

**Comment by italomlp** [comment]
@jpdemagalhaes I'm passing `fieldName` and `registerField` like in the docs. But I agree that is can be an issue in the use of the `useEffect` hook.
By the way, if I use it as you described, ESLint give me some errors (in a `create-react-app` project):

```
React Hook useEffect has a missing dependency: 'registerField'. Either include it or remove the dependency array.
Mutable values like 'ref.current' aren't valid dependencies because mutating them doesn't re-render the component. eslint(react-hooks/exhaustive-deps)
```

So, we have to add the `// eslint-disable-line` to work? Is there a better way to make it without disabling eslint in this specific case?

**Comment by italomlp** [comment]
Well, I think I got an older version of the docs or something like this. Sorry, my mistake. About eslint warning, I'll open a new issue. Thanks.

**Comment by PejmanNik** [comment]
I think we are ignoring hooks rule here. we don't need to add `ref.current` and `registerField` must be added as a dependency.
please reopen the issue.

**Comment by emilioheinz** [comment]
I think the best solution is adding a `if` before call the `registerField` function.

```js
useEffect(() => {
    if (ref.current) {
      registerField({
        name: fieldName,
        ref: ref.current,
        path: 'props.selected',
        clearValue: pickerRef => {
          pickerRef.clear()
        },
      })
    }
  }, [fieldName, registerField])
```

I think we need to improve the docs with that because the infinity render still happening without the `if` condition.

**Comment by diego3g** [comment]
@PejmanNik If we use `registerField` inside hook dependencies then it executes infinitely, if you have any thoughts why this is happening please feel free to open a Pull Request. At least for now, even the rules of hooks saying about it dependencies, we'll keep this format that is the only format we got it working right now.

**Comment by DeeSouza** [comment]
> ```js
>   useEffect(() => {
> ```

I solved my problem from infinite loop removing function `registerField()` from array dependencies.
