### ISSUE TITLE
Pass a React component as prop to an input.

### ISSUE THREAD

**Issue by marcelobarreto** [Rocketseat/unform#53]
**What would you like to be added**:
Option to pass a React component as a prop

**Why is this needed**:
If I'm using a UI lib such as Material-UI, I could pass my custom component.

**Is your enhancement request related to a problem? Please describe.**
I guess no, maybe #49 

I can get this one if you guys like the idea :smile:

**Comment by diego3g** [comment]
@marcelobarreto Unform already exposes the `withField` API so you can use it to create your custom form element. I don't know if receiving a React Component as a prop is the best idea.

**Comment by marceloF5** [comment]
@diego3g what is the best way for application that's already has input components been defined before?

**Comment by diego3g** [comment]
@marceloF5 The `useField` API exposes full integration for every text input. The only requisite is that the element must have an easy way of access to its value using ref, and it needs also do be clearable by setting it value to empty or calling a function.

The "Custom elements" docs have more details about that.

**Comment by marceloF5** [comment]
nice, tks @diego3g 
I wrote a simple example here: https://codesandbox.io/s/wizardly-allen-46n68

**Comment by diego3g** [comment]
Closing the issue, feel free to reopen it.
