### ISSUE TITLE
Translate README to pt-BR

### ISSUE THREAD

**Issue by alexandreramosdev** [Rocketseat/unform#55]
Olá @diego3g, I would like to know if I can do the translation of the README to have an i18n improve! What do you think?

**Comment by diego3g** [comment]
@alexandreramosdev Hi Alexandre, we want to keep all issues and contributions to this repo in english so can you please translate the original message here?

We have thoughts about i18n but nothing decided yet. Maybe we could create an docs website instead of using only Github because here we have really poor support for i18n as new markdowns would be created for every language.

**Comment by danilosales** [comment]
I suggest create others docs translated on folder translated, and in the README link to the doc translated.

**Comment by leonardobrito** [comment]
For docs website, maybe we can use [Docusaurus](https://docusaurus.io/), they allows easy translation and localization and the site can be host by [github pages](https://pages.github.com/). Sound good?

**Comment by diego3g** [comment]
@leonardobrito Sounds great. We are using Docosaurus here: http://docs.rocketseat.dev

Repository: https://github.com/rocketseat/docs

**Comment by leonardobrito** [comment]
Nice @diego3g , how to proceed with that? We have to send a pull request to [https://github.com/rocketseat/docs](https://github.com/rocketseat/docs) or unform will have his own repository/website of docs. Or is too early to do that. If possible i will like to contribute with that chore.

**Comment by diego3g** [comment]
@leonardobrito I think Unform can have it's own documentation

**Comment by leonardobrito** [comment]
So the @rocketseat will create another repository for his documentation? With a docusaurus project.

**Comment by diego3g** [comment]
@leonardobrito Maybe will be better if we have a docs folder inside the same repo.

**Comment by alexandreramosdev** [comment]
@diego3g The Rockeatseat have the styleguide for create website doc do unform! I like about think that create website with Docosaurus in folder docs inside this repor.

**Comment by leonardobrito** [comment]
@alexandreramosdev i guess a folder named docs or documentation, like the example folder will be great. What do you folks think?

**Comment by mmCodingjs** [comment]
I have seen others repositories and docs folder would be great.
Inside that folder we can create a readme for each language

**Comment by leonardobrito** [comment]
If is okay for all, i can publish an PR with it soon, the folder docs with Docusaurus project and the initial documentation.

**Comment by diego3g** [comment]
This issue is being treated in #80.

**Comment by brendonguedes** [comment]
O próprio Google, acredito que outros navegadores também permitam, que o usuário adicione uma extensão para tradução automática de outras línguas, como inglês para português brasileiro.

Basta acessar as configurações para adicionar a extensão.

**Comment by jpedroschmitz** [comment]
Hey guys, we have decided now to keep our efforts on the Unform API, so the docs will keep in English. As the project grows, we are going to focus on i18n. As we finish it we will create new docs where you all can contribute (in any language). We really appreciate your efforts in making this happen 💜
