### ISSUE TITLE
Não da para usar esta biblioteca caso o projeto use o ant design

### ISSUE THREAD

**Issue by anaalice-agcom** [Rocketseat/unform#56]
**Description of bug**
Hi Diego, i'm using ant design library in my project and i'm needing use your library too, but ant design library  uses Input as a name like your project. How can i fix this conflict?

**To Reproduce**

**Expected behavior**

**Exception or Error**

<pre><code>

</code></pre>

**Screenshots**

**Environment:**

**Additional context**

**Comment by diego3g** [comment]
Hello @anaalice-agcom, we are using only english to contributions so please translate the original message.

You can import Unform Input with any name you want, like:

```js
import { Input as UnformInput } from '@rocketseat/unform`;
```

Also, i don't think it's a bug, just a documentation issue.

**Comment by anaalice-agcom** [comment]
This should work. Thanks

**Comment by diego3g** [comment]
I'll close the issue but feel free to reopen it if you face any problems :)
