### ISSUE TITLE
Use react-input-mask and unform

### ISSUE THREAD

**Issue by risoaldo** [Rocketseat/unform#57]
**Description of issue**
I'm trying use unform library, but i can't see a way to use react-input-mask too. Can i use unform with a className?

**Usage example**
`<InputMask  name="end_cep" mask="99999-999" maskChar="_" placeholder="Ex: 00000-000" className="ant-input" />`

**Comment by italomlp** [comment]
You can use it the same way React Select and React DatePicker, with the `useField` hook. See the `Custom components` section in the docs.

**Comment by risoaldo** [comment]
It's a great idea. Thanks

**Comment by garciawell** [comment]
@risoaldo 
Example with library-input-input-mask.

Note: To clear the values ​​I needed to call the function "setInputValue" passing the value as null

Maybe we can add this example to the lib documentation, what do you think? @diego3g 


`import React, { useRef, useEffect, useState } from "react";
import InputMask from "react-input-mask";

import { useField } from "../../../lib";

export default function Mask({ name, inputMask }) {
  const ref = useRef(null);
  const { fieldName, registerField, defaultValue, error } = useField(name);
  const [mask, setMask] = useState(defaultValue);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: ref.current,
      path: "props.value",
      clearValue: pickerRef => {
        pickerRef.setInputValue(null);
      }
    });
  }, [ref.current, fieldName]);

  function handleMask(e) {
    const { value } = e.target;
    return setMask(value);
  }

  return (
    <>
      <InputMask
        name={fieldName}
        mask={inputMask}
        value={mask}
        onChange={e => handleMask(e)}
        ref={ref}
      />
      {error && <span>{error}</span>}
    </>
  );
}
`

**Comment by santospatrick** [comment]
> }, [ref.current, fieldName]);

this example does not work when form has `initialData prop`

**Comment by santospatrick** [comment]
@garciawell your example does not work when form has `initialData` prop (when form data needs to be fullfilled by an async call)

**Comment by giorgiofellipe** [comment]
@santospatrick you've managed to fix it or found any workaround?

**Comment by santospatrick** [comment]
@giorgiofellipe a temporary solution was only render the input when `initialData.property` has loaded

**Comment by garciawell** [comment]
@santospatrick 
Sorry for the delay, I had not tested making an asynchronous call and adding an initial value.



This seems to be a global problem, in which a user comments the same issue by referencing the form in which it is possible to reassign the initial value.

https://github.com/Rocketseat/unform/issues/149

initialData.property 
It worked ?

**Comment by giorgiofellipe** [comment]
Managed to get it working as intended by setting mask again when `defaultValue` changes.

Also, you may face this warning `A component is changing a controlled input of type undefined to be uncontrolled.`. I've got rid of it by passing as value an empty string if `defaultValue` is falsy [(source)](https://stackoverflow.com/questions/37427508/react-changing-an-uncontrolled-input).


```javascript
  const [mask, setMask] = useState(defaultValue || '');

  useEffect(() => {
    setMask(defaultValue || '');
  }, [defaultValue]);
```

**Comment by maiconfriedel** [comment]
Thanks @giorgiofellipe and @garciawell  ! You guys saved me! I was having the same issue in my code, and that solution saved me! 😄
