### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by risoaldo** [Rocketseat/unform#58]
**Description of bug**
I just put a Input and have an error

`<UnformInput className="ant-input" style={{ width: '90%' }} />`
**To Reproduce**

**Expected behavior**
Cannot read property 'indexOf' of undefined

**Exception or Error**

<pre><code>

</code></pre>

**Screenshots**
![2019-05-20](https://user-images.githubusercontent.com/21092692/58031586-163b3300-7af7-11e9-99b3-85bc76979d3f.png)

**Environment:**

**Additional context**

**Comment by diego3g** [comment]
Can you please provide an example of your code inside Code Sandbox? http://codesandbox.io

**Comment by risoaldo** [comment]
https://codesandbox.io/embed/lucid-brown-olk23

**Comment by diego3g** [comment]
@risoaldo Your example inside Code Sandbox is not working, it's missing dependencies and other parts of the code, can you take a look at it?

**Comment by risoaldo** [comment]
The code involves many components, I'm just picking up a type of person and according to the type the form is displayed, when I change from PF to PJ it gives this error

![image](https://user-images.githubusercontent.com/21092692/58041280-172b8f00-7b0e-11e9-9213-c300176789f7.png)

**Comment by risoaldo** [comment]
To better understand, its just a simple form. I used unform in another foms and worked just fine, but in this one i did the same way and a had this error. I have two forms, one for juridic person and another for fisic person. The user has to choose who he is using a Select, and the form shows up. In fisic person (comes fisic person for default) form the unform works, but when i change to juridic person, shows up this error

**Comment by diego3g** [comment]
I can't figure out what's happening in your code without a code example, it can be many things. Can you please try to provide one working code example that i can see your code and it working?

**Comment by risoaldo** [comment]
Diego, here is an example of what is happening
When we choose Pessoa Juridica on the select, in the console shows the error message
https://codesandbox.io/s/optimistic-hooks-5fjv1

**Comment by jpdemagalhaes** [comment]
@risoaldo in the `pjForm.js` you forgot to pass the `name` props to the `<UnformInput>`.

Therefore `unform` cannot register your fields. Adding the `name` prop to all fields fixes the problem. Can you verify this?

**Comment by risoaldo** [comment]
That solved my problem. Thank you
