### ISSUE TITLE
Add new prop "multiline" to input and remove Textarea

### ISSUE THREAD

**Issue by diego3g** [Rocketseat/unform#59]
**What would you like to be added**:

Add a prop to Input:
```js
<Input multiline />
```
And now it will act as a `textarea`.

**Why is this needed**:

Input and textarea are common elements, they both act the same way and we have redundant code between the two components.

**Is your enhancement request related to a problem? Please describe.**

No.

**Additional context**

React Native already do this way, so why not :)

**Comment by dudusotero** [comment]
A Conditional render of a textarea instead of an input will be the solution for this?

**Comment by jpdemagalhaes** [comment]
Sounds good to me!

I just took a look at the `Input.tsx` and `Textarea.tsx` files and they even have the same amount of lines 😄 .

Unifying this would be nice.

Could you make a PR about this @diego3g? I also agree with @dudusotero a simple conditional render would be enough I think.

**Comment by pellizzetti** [comment]
Makes sense to me, they are pretty much the same. Let's remove this redundancy! 😄

**Comment by diego3g** [comment]
@dudusotero Yeah, i'm working on that already! Sending a PR in a few minutes.

**Comment by TiagoCunhaF** [comment]
@diego3g , não teria sido melhor, manter o componente Textarea, e apenas modificar o mesmo para chamar o input com o parâmetro multiline ? Pois dessa forma não quebraria a aplicação de quem já implementou usando o unform e utilizou o componente Textarea. (da mesma forma que no seu video, sua remoção quebrou testes já existentes)

**Comment by viniciushernandes** [comment]
It makes sense to me. Less redundancy!
