### ISSUE TITLE
resetForm behaviour

### ISSUE THREAD

**Issue by rfbezerra** [Rocketseat/unform#67]
**What would you like to be added**:
We have a resetForm method to be called after form submission. When this method is called, all fields will be cleared, even if default value supplied.
I think this behaviour is wrong if initialData supplied. I think the resetForm should set the initialData to fields.

**Why is this needed**:
Maybe, change this behaviour to reset fields to initialData and add another property to clear fields values.
_clearForm_ and _resetForm_?

**Comment by pellizzetti** [comment]
Another approach is to allow some kind of flag to be passed to `resetForm`, like:

```js
function handleSubmit(data, { resetForm }) {
  resetForm();
  // ---
  resetForm({ clean: true }); //
};
```
or, reusing `initialData`, maybe?

```js
const initialData = {
  name: 'John Doe',
  address: {
    street: 'Sample Avenue',
  },
}

function handleSubmit(data, { resetForm }) {
  resetForm({ initialData });
};
```

**Comment by italomlp** [comment]
I think that is not the responsibility of the developer to pass the initial data again to reset form. So, I like the first approach you suggested @pellizzetti. +1 for that

**Comment by rfbezerra** [comment]
I agree with first approach, but with a property in Form component.
Maybe, a new _options_ object to specify things like that.

**Comment by pellizzetti** [comment]
@rfbezerra Not a bad approach but, IMHO, having to set a option in `Form` to define this kind of behavior would surely reduce flexibility and make worse for users who want to resets to `initialData` or not conditionally.

**Comment by MorenoMdz** [comment]
Just to confirm if I understood it, here when I call resetForm() it goes back to the initial values I have set, and you want to be able to check if it should reset to the initial data or no data, correct?

**Comment by jpdemagalhaes** [comment]
I think that we should follow @pellizzetti second suggestion, which will give the developers more flexibility to handle the reset how they see fit.

An example of this would be when the form is used to save user data, and you can call `resetForm` with the data that got returned by API, like this:

```js
async function handleSubmit(data, { resetForm }) {
  // just an example of an API call
  const { data: newData } = await api.put('/user', data);

  // Instead of reseting the form to its initialData, it will reset with newData
  resetForm({ newData });
}
```

If one of you guys could submit a PR about this, we'd be happy to take a look ❤️

**Comment by rfbezerra** [comment]
I'll try to make a PR with this things and we can talk over
