### ISSUE TITLE
 Contribution Guidelines link does not redirect to documentation

### ISSUE THREAD

**Issue by iltonkp** [Rocketseat/unform#69]
**Description of issue**

Clicking the Contribution Guidelines link is not redirected to a session.

**Usage example**

Go to the github.com/rocketseat/unform link -> access the documentation in the Index section -> click the Contribution Guidelines link.

**Comment by Ruttmann** [comment]
There's a small typo in the line 68 of the README.md.

Where you see:
`- [Contribution Guidelines](#contributing-guide)`

Should be:
`- [Contribution Guidelines](#contribution-guidelines)`

I'll create a PR to address this issue.

**Comment by pellizzetti** [comment]
@iltonkp @Ruttmann Nice catch, If any of you guys want to open a PR, I'll be waiting. Thx 💟

**Comment by jpdemagalhaes** [comment]
Closing this since it was done on #35

Thanks @iltonkp @Ruttmann ❤️
