### ISSUE TITLE
Lost Textarea component after issue #59

### ISSUE THREAD

**Issue by TiagoCunhaF** [Rocketseat/unform#74]
The componente Textarea was replaced to input with multiline attribute, but for this is not a good solution because this broken all applications was using Textarea component.
https://github.com/Rocketseat/unform/issues/59

In my opinion in this moment when de library is very new, its not a very big problem, but if I has multiple applications using unform and components has removed because other people resolve remove in new feacture, surely I would decide to stop using unform.

My suggestion is maintenance TextArea component and this component call the input with multiline param.

Concept bug, is not a functional bug at moment.

**Comment by jpdemagalhaes** [comment]
@TiagoCunhaF thanks for the suggestion! I agree with you, I'll be submitting a PR for this shortly. I was already working on it 😄 

Thanks nonetheless ❤️
