### ISSUE TITLE
Run lint-staged on tests and example files

### ISSUE THREAD

**Issue by diego3g** [Rocketseat/unform#78]
**What would you like to be added**:

Run lint-staged in tests and example folder.

**Why is this needed**:

People have different editors and configuration and sometimes Prettier is messing with those files and Pull Requests get rejected because of style guide.

**Is your enhancement request related to a problem? Please describe.**

Not a problem itself, but there are a lot of PR's with linting problems.

**Additional context**

Maybe something like this solve the issue:

```json
"lint-staged": {
  "lib/**/*.{ts,tsx}": [
    "eslint --fix",
    "prettier --write",
    "jest --bail --findRelatedTests"
  ],
  "__tests__/**/*.{ts,tsx}" : [
    "eslint --fix",
    "prettier --write"
  ],
  "example/**/*.{ts,tsx}" : [
    "eslint --fix",
    "prettier --write"
  ]
},
```

**Comment by italomlp** [comment]
I think that in some cases the configuration of the editor can change `*.md` files too (happened with me). So, I suggest adding a configuration in lint-staged to achieve this too.
