### ISSUE TITLE
focus cycle

### ISSUE THREAD

**Issue by petkovic43** [Rocketseat/unform#79]
I would like to propose two new features, one indicating which should be the first field to receive the focus and the other indicating the next field where the focus should jump when the user press enter or tab. Thus, in the resetform the focus could return to the first field and cycle again

**Comment by diego3g** [comment]
About the focus, did you try adding `autofocus` prop to input? Also, the focus order may be controlled by tabindex prop, did you try using that too?

**Comment by jpedroschmitz** [comment]
I'll be closing this @petkovic43 as it seems that @diego3g  proposed a solution and to expand on that, unform IMO should not be responsible for that, it's easy enough to do it with HTML5 alone.

But feel free to reopen this issue in case you feel like we missed something ❤️
