### ISSUE TITLE
Set the resetForm call as an element attribute

### ISSUE THREAD

**Issue by MorenoMdz** [Rocketseat/unform#86]
**What would you like to be added:**
Set if the form is reset after submitting with a tag attribute as in this example:
```
        <Form onSubmit={this.handleUpdate} resetForm>
          <FormInput type="hidden" name="id" value={item.id} />
          <FormInput type="text" name="text" placeholder={item.text} />
          <FormInput type="text" name="type" placeholder={item.type} />
          <FormInput type="text" name="value" placeholder={item.value} />
          <FormInput type="text" name="duration" placeholder={item.duration} />
          <button type="submit" className="teal-btn">
            Update
          </button>
        </Form>
```

This could be done by checking if the `resetForm` prop is present, it can also be used to handle issue #67 if that change is implemented by passing the props data to specify what time of reset is done.

**Why is this needed:**
It may be better semantic wise and you may need to reset one form but not another while using the same submit method in both.

**Is your enhancement request related to a problem? Please describe.**
No.

**Comment by jpdemagalhaes** [comment]
@MorenoMdz, I don't really get what's your use case here. It seems like you want to use one submit function for more than one `<Form>`, is this it?

If this is the case, I don't think that it's healthy to do that, things can get messy real quick. Either way, if you really need/want to do that, you could simply make a function that handles your submits and gets passed an argument to identify which form it is, then you can filter it inside your function. 

Also, I don't think that passing a `resetForm` prop is necessary on `<Form>`, since we already provide the following syntax:

```js
function handleSubmit(data, { resetForm }) {
  // clear form data
  resetForm();
}

<Form onSubmit={handleSubmit}>
  <Input name="username" />
</Form>
```

**Comment by MorenoMdz** [comment]
Yes, the idea is in cases, yet rare, where you want to have a single submit method, it may be another way to specify that a form must be reset after submission. Also, it is semantically more explicit to have the reset call in the form declaration that in the JS code. 

The idea is to have the form check if a resetForm prop is present and if it has any specific reset data to follow (which fields to reset to default values, which fields to not reset at all etc). Also, the `defaultValues' option is set in the form tag but the reset is set after in the submit, both could use the same configuration design, as a prop.

**Comment by diego3g** [comment]
@MorenoMdz I don't agree, i think resetForm by it's name is a function, not an attribute. We are adding more functionality to resetForm (as you can see here #67) and bringing it as an attribute will loose all of it flexibility.

**Comment by MorenoMdz** [comment]
While I understand the naming as a verb is more suit for a function, names can be changed of course, it should not lose flexibility as in the same way we pass an object to specify the initial values an object could also be passed to tell the form how it should handle the reset. 

Either way, I feel the proposals from #67 have priority. Thanks.

**Comment by MorenoMdz** [comment]
I will close this one, for now, I may bring it later in the future as and if more use cases appear.

"Keep your minds open to only then make something that's truly new."
