### ISSUE TITLE
Add a component documentation

### ISSUE THREAD

**Issue by dudusotero** [Rocketseat/unform#9]
Will be nice to use some type of component documentation like [Docz](https://github.com/pedronauck/docz).

Using it will make easier for everyone looking for answers

**Comment by diego3g** [comment]
Hi @dudusotero, i was testing Docz with TypeScript and i got some problems while trying to render PropsTable (https://www.docz.site/docs/built-ins-components#component-props). 

Maybe related to this issue: https://github.com/pedronauck/docz/issues/138

As soon as i didn't manage to fix it, i leaved it this way. 

I'm also taking a look at Storybook as an alternative to Docz.

**Comment by dudusotero** [comment]
If you create a branch and send me the actual implementation, I could try help you to fix it.

**Comment by diego3g** [comment]
@dudusotero Actually i changed all the docs project to pure Javascript to make it work, so i don't have the TS version anymore. But you can just create a new project with docz and TypeScript and try to render PropTable.

**Comment by dudusotero** [comment]
@diego3g I will make it, and I will share with you my results ;)

**Comment by diego3g** [comment]
Hi @dudusotero, i'll close the issue since you'll probably take some time to test it, but feel free to reopen it :)

**Comment by dudusotero** [comment]
I finally get some time to do some tests, and now I was able to make docz works in a typescript project.
There are problems in some dependencies of docz, so we are able to do a workaround by adding [acorn@6.0.5](https://github.com/acornjs/acorn) to the project's dev dependencies.

Just run `yarn add acorn@6.0.5 -D` and all starts to work perfectly.
