### ISSUE TITLE
Examples to React Hooks

### ISSUE THREAD

**Issue by emersonlaurentino** [Rocketseat/unform#90]
**Description of issue**

There are no example to React Hooks.

**Usage example**

Add some examples to React Hooks.

**Comment by jpdemagalhaes** [comment]
@emersonlaurentino, I couldn't quite get what you're saying, could you describe a little better what you mean?

Unform uses hooks internally, and exposes `useField()` for usage, but there is already an example on our docs about it.

**Comment by emersonlaurentino** [comment]
@jpdemagalhaes I thought one of his features would be to use hooks. So I asked for more examples of how to use it with hooks. Since I understood that it was created with hooks and not that it can be used with one, it does not make sense that issue.

**Comment by jpdemagalhaes** [comment]
No problem! Just a quick heads up we expose `useField` which is a Hook, this is used to create custom types of fields that do not come along with Unform. You can check that out [here.](https://github.com/Rocketseat/unform#custom-elements)

I'll be closing this issue then! But feel free to reopen this one or open another one ❤️
