### ISSUE TITLE
Function components cannot be given refs

### ISSUE THREAD

**Issue by xbral** [Rocketseat/unform#93]
When I try to reference a function component it returns: Function components can not be given refs. Attempts to access this ref will fail. 

The component used was:
```jsx
import { MuiPickersUtilsProvider, KeyboardDatePicker } from '@material-ui/pickers';

const DatePickers = ({ name, ...rest }) => {
  const ref = useRef();
  const { fieldName, registerField, defaultValue, error } = useField(name);
  const [selected, setSelected] = useState(defaultValue);

  useEffect(() => {
    registerField({
      name: fieldName,
      ref: ref.current,
      path: 'props.selected',
      clearValue: pickerRef => {
        pickerRef.clear();
      },
    });
  }, [ref.current, fieldName]);

  return (
    <KeyboardDatePicker 
      ref={ref} 
      name={fieldName}
    />
  );
};
```

**Comment by diego3g** [comment]
Hi @xbral, not every component supports `ref` but it's not a problem with Unform itself, maybe Material UI is not forwarding the ref to the input element inside `KeyboardDatePicker`. As you can see here, there is no ref property (https://material-ui-pickers.dev/api/KeyboardDatePicker). 

The same documentation is saying that `Any prop not recognized by the pickers and their sub-components are passed down to material-ui TextField component.` but this is not happening as the `ref` property is not being passed down to `TextField` from Material UI.

I really recommend you opening a issue inside https://github.com/mui-org/material-ui-pickers

**Comment by xbral** [comment]
> Hi @xbral, not every component supports `ref` but it's not a problem with Unform itself, maybe Material UI is not forwarding the ref to the input element inside `KeyboardDatePicker`. As you can see here, there is no ref property (https://material-ui-pickers.dev/api/KeyboardDatePicker).
> 
> The same documentation is saying that `Any prop not recognized by the pickers and their sub-components are passed down to material-ui TextField component.` but this is not happening as the `ref` property is not being passed down to `TextField` from Material UI.
> 
> I really recommend you opening a issue inside https://github.com/mui-org/material-ui-pickers

Great... I'll do that now... tks...
