### ISSUE TITLE
Input multiline does not recive state

### ISSUE THREAD

**Issue by victorhermes** [Rocketseat/unform#95]
Not reported!

**Description of bug**
I was using componentWillReceiveProps(nextProps) to get the currently prop and using setState to add the prop to a state. So, I could to call the state and set the initialData with this state and show to user the text into the input. This was good! The text appeared in the Input, but not in the Input with multiline, so when I removed the multiline property, the text was shown.

**To Reproduce**
I think the bug is a error with multiline property, because when I remove the multiline, the text is shown.

**Expected behavior**
1) Set componentWillReceiveProps(nextProps) reciving some data.
2) Set a state into the componentWillReceiveProps(nextProps) passing the prop.
3) Consume the data in the initialData.
4) Nothing appears in the Input multiline.

**Exception or Error**
I hope the text is showing inside the input.

<pre><code>
  state = {
    data: {},
  };

  componentWillReceiveProps(nextProps) {
    const data = nextProps.tool;
    this.setState({ data });
  }

render() {
    const { data } = this.state;
    const initialData = {
      description: data.description || '',
    };
    return (
       Form schema={schema} onSubmit={this.handleSubmit} initialData={initialData}
            Input multiline name="description"
       Form
    )
}
</pre></code>

**Environment:**
- Windows 10 Enterprise
- Browser: Mozilla (67.0)
- Node v11.11.0

**Screenshots**
![carbon](https://user-images.githubusercontent.com/25070025/59075285-32d0bc80-88a6-11e9-9848-4b4b85863251.png)

**Comment by VilsonJrCorrea** [comment]
Hey brother, have you tried something like that in the props of component Input? `value={initialData.description}`

**Comment by victorhermes** [comment]
@VilsonJrCorrea It worked. Thank u!

**Comment by arthurdenner** [comment]
@victorhermes, in case you don't understand *why* you need to pass the `value` prop here, here are the concepts of [controlled](https://reactjs.org/docs/forms.html#controlled-components) and [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html).
